Repository kosmos-io/kosmos, pull requests merged in 2023-09, with the labels that each got.

#11 feat: update crd
  deploy/crds/kosmos.io_clusters.yaml
  pkg/apis/clusterlink/v1alpha1/cluster_types.go
  pkg/apis/clusterlink/v1alpha1/zz_generated.deepcopy.go
  pkg/clusterlinkctl/initmaster/ctlmaster/manifests_crd.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: size/S, approved, lgtm

#12 fix: fix the bug of debounce
  cmd/agent/app/agent.go
  go.mod
  go.sum
  vendor/github.com/bep/debounce/.gitignore
  vendor/github.com/bep/debounce/LICENSE
  vendor/github.com/bep/debounce/README.md
  vendor/github.com/bep/debounce/debounce.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#15 move projectpath and generate to hack directory
  hack/generate/generate.go
  hack/projectpath/path.go
  hack/update-crds.sh
  test/e2e/framework/cluster.go
Labels: size/XS, approved, lgtm

#17 add pod affinity
  deploy/clusterlink-network-manager.yml
  deploy/clusterlink-operator.yml
Labels: size/S, approved, lgtm

#21 change some package name
  cmd/link-agent/app/agent.go
  cmd/link-agent/app/options/options.go
  cmd/link-agent/app/options/validation.go
  cmd/link-agent/main.go
  cmd/link-controller-manager/app/controller-manager.go
  cmd/link-controller-manager/app/controllerstarter.go
  cmd/link-controller-manager/app/core.go
  cmd/link-controller-manager/app/options/options.go
  cmd/link-controller-manager/main.go
  cmd/link-elector/app/elector.go
  cmd/link-elector/app/options/options.go
  cmd/link-elector/main.go
  cmd/link-proxy/app/clusterlink-proxy.go
  cmd/link-proxy/app/options/options.go
  cmd/link-proxy/main.go
  hack/util.sh
  pkg/link-agent/controller.go
  pkg/link-agent/network-manager/network_manager.go
  pkg/link-controllers/calicoippool/calicoippool_controller.go
  pkg/link-controllers/calicoippool/calicoippool_controller_test.go
  pkg/link-controllers/calicoippool/manifests.go
  pkg/link-controllers/cluster/cluster_controller.go
  pkg/link-controllers/cluster/helper.go
  pkg/link-controllers/context/context.go
  pkg/link-controllers/node/node_controller.go
  pkg/link-controllers/nodecidr/adapter.go
  pkg/link-controllers/nodecidr/nodecidr_controller.go
Labels: size/M, approved, lgtm

#24 feat: Add kosmos pod controller interface
  cmd/knode-manager/app/config/config.go
  cmd/knode-manager/app/manager.go
  cmd/knode-manager/app/options/options.go
  pkg/clusterrouter/knodemanager/knode/knode.go
  pkg/knode-manager/adapters/interface.go
  pkg/knode-manager/adapters/k8s/node.go
  pkg/knode-manager/adapters/k8s/pod.go
  pkg/knode-manager/controllers/node.go
  pkg/knode-manager/controllers/pod.go
  pkg/knode-manager/knode.go
  pkg/knode-manager/knodemanager.go
  pkg/knode-manager/result.go
  pkg/knode-manager/utils/util.go
Labels: approved, lgtm, size/L

#26 feat: kosmosctl support using the install and uninstall command
  Makefile
  cmd/kosmosctl/main.go
  go.mod
  go.sum
  hack/util.sh
  pkg/kosmosctl/get/get.go
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/kosmosctl.go
  pkg/kosmosctl/manifest/manifest_crds.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/kosmosctl/uninstall/uninstall.go
  pkg/kosmosctl/util/builder.go
  vendor/github.com/fatih/camelcase/.travis.yml
  vendor/github.com/fatih/camelcase/LICENSE.md
  vendor/github.com/fatih/camelcase/README.md
  vendor/github.com/fatih/camelcase/camelcase.go
  vendor/k8s.io/client-go/util/certificate/csr/csr.go
  vendor/k8s.io/kubectl/pkg/apps/kind_visitor.go
  vendor/k8s.io/kubectl/pkg/cmd/apiresources/apiresources.go
  vendor/k8s.io/kubectl/pkg/cmd/apiresources/apiversions.go
  vendor/k8s.io/kubectl/pkg/cmd/delete/delete.go
  vendor/k8s.io/kubectl/pkg/cmd/delete/delete_flags.go
  vendor/k8s.io/kubectl/pkg/cmd/util/podcmd/podcmd.go
  vendor/k8s.io/kubectl/pkg/cmd/wait/wait.go
  vendor/k8s.io/kubectl/pkg/describe/describe.go
  vendor/k8s.io/kubectl/pkg/describe/interface.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/attachablepodforobject.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/canbeexposed.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/helpers.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/history.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/historyviewer.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/interface.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/logsforobject.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/mapbasedselectorforobject.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/objectpauser.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/objectrestarter.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/objectresumer.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/portsforobject.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/protocolsforobject.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/rollback.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/rollbacker.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/rollout_status.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/statusviewer.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/updatepodspec.go
  vendor/k8s.io/kubectl/pkg/util/certificate/certificate.go
  vendor/k8s.io/kubectl/pkg/util/completion/completion.go
  vendor/k8s.io/kubectl/pkg/util/deployment/deployment.go
  vendor/k8s.io/kubectl/pkg/util/event/sorted_event_list.go
  vendor/k8s.io/kubectl/pkg/util/fieldpath/fieldpath.go
  vendor/k8s.io/kubectl/pkg/util/podutils/podutils.go
  vendor/k8s.io/kubectl/pkg/util/qos/qos.go
  vendor/k8s.io/kubectl/pkg/util/rbac/rbac.go
  vendor/k8s.io/kubectl/pkg/util/resource/resource.go
  vendor/k8s.io/kubectl/pkg/util/storage/storage.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#25 add ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/flaking-test.md
  .github/ISSUE_TEMPLATE/good-first.md
  .github/ISSUE_TEMPLATE/question.md
Labels: size/M, approved, lgtm, ok-to-test

#27 feat: init node controller
  cmd/knode-manager/app/config/config.go
  cmd/knode-manager/app/options/options.go
  deploy/crds/kosmos.io_knodes.yaml
  pkg/apis/kosmos/v1alpha1/knode_types.go
  pkg/knode-manager/controllers/node.go
  pkg/knode-manager/knode.go
  pkg/knode-manager/knodemanager.go
Labels: approved, lgtm, size/L

#30 block add overlapped ippool
  Makefile
  hack/cluster.sh
  pkg/link-controllers/calicoippool/calicoippool_controller.go
  pkg/link-controllers/calicoippool/calicoippool_controller_test.go
  pkg/network-manager/handlers/pod_routes.go
  pkg/network-manager/helpers/network.go
  pkg/network-manager/helpers/network_test.go
  pkg/utils/net/network.go
  pkg/utils/net/network_test.go
Labels: approved, lgtm, size/L

#31 fix: kosmosctl add floater logic and remove linkctl
  pkg/clusterlinkctl/ctl.go
  pkg/clusterlinkctl/floaterclient/cluster-helper.go
  pkg/clusterlinkctl/floaterclient/doctor.go
  pkg/clusterlinkctl/floaterclient/floater.go
  pkg/clusterlinkctl/initmaster/ctlmaster/deploy_configmap.go
  pkg/clusterlinkctl/initmaster/ctlmaster/deploy_crd.go
  pkg/clusterlinkctl/initmaster/ctlmaster/deploy_deployments.go
  pkg/clusterlinkctl/initmaster/ctlmaster/deploy_rbac.go
  pkg/clusterlinkctl/initmaster/ctlmaster/install.go
  pkg/clusterlinkctl/initmaster/ctlmaster/manifests_configmap.go
  pkg/clusterlinkctl/initmaster/ctlmaster/manifests_crd.go
  pkg/clusterlinkctl/initmaster/ctlmaster/manifests_deployments.go
  pkg/clusterlinkctl/initmaster/ctlmaster/manifests_rbac.go
  pkg/clusterlinkctl/initmaster/ctlmaster/uninstall.go
  pkg/clusterlinkctl/initmaster/initmaster.go
  pkg/clusterlinkctl/membercurd/membercurd.go
  pkg/clusterlinkctl/membercurd/options.go
  pkg/clusterlinkctl/util/apiclient/apiclient.go
  pkg/clusterlinkctl/util/command_group.go
  pkg/kosmosctl/floater/command/curl.go
  pkg/kosmosctl/floater/command/interface.go
  pkg/kosmosctl/floater/command/ping.go
  pkg/kosmosctl/floater/doctor.go
  pkg/kosmosctl/floater/floater.go
  pkg/kosmosctl/floater/netmap/netmap.go
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/kosmosctl.go
  pkg/kosmosctl/manifest/manifest_clusterrolebindings.go
  pkg/kosmosctl/manifest/manifest_clusterroles.go
  pkg/kosmosctl/manifest/manifest_daemonsets.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/kosmosctl/manifest/manifest_serviceaccounts.go
  pkg/kosmosctl/uninstall/uninstall.go
  pkg/kosmosctl/util/builder.go
  pkg/kosmosctl/util/check.go
Labels: approved, lgtm, size/XXL

#34 add duanmengkk and yuleichun-striving to scheduler module code owners
  OWNERS
  cmd/koslet/OWNERS
  cmd/scheduler/OWNERS
  vendor/OWNERS
Labels: size/S, approved, lgtm

#35 Add kosmosctl code owners
  pkg/kosmosctl/OWNERS
Labels: size/XS, approved, lgtm

#32 feat: kosmosctl join and unjoin
  go.mod
  go.sum
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/kosmosctl.go
  pkg/kosmosctl/manifest/manifest_clusterrolebindings.go
  pkg/kosmosctl/manifest/manifest_clusterroles.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/kosmosctl/manifest/manifest_serviceaccounts.go
  pkg/kosmosctl/unjoin/unjoin.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/yaml/meta.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/yaml/yaml.go
  vendor/k8s.io/kube-aggregator/LICENSE
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/helpers.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/defaults.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.pb.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.conversion.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.deepcopy.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.defaults.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/defaults.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/generated.pb.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/generated.proto
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/zz_generated.deepcopy.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/clientset.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme/register.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/generated_expansion.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/generated_expansion.go
  vendor/k8s.io/utils/env/doc.go
  vendor/k8s.io/utils/env/env.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#33 add scheduler taint logic for knode
  cmd/scheduler/main.go
  pkg/scheduler/OWNERS
  pkg/scheduler/lifted/helpers/tainttoleration.go
  pkg/scheduler/lifted/plugins/knodetainttoleration/knode_tainttoleration.go
Labels: approved, lgtm, size/L

#36 fix: kosmosctl install image issue
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/manifest/manifest_crds.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/kosmosctl/util/builder.go
Labels: size/S, approved, lgtm

#37 fix common Adapter bug
  pkg/link-controllers/nodecidr/adapter.go
Labels: size/XS, approved, lgtm

#40 fix: kosmosctl unjoin wait time
  pkg/kosmosctl/unjoin/unjoin.go
Labels: size/XS, approved, lgtm

#45 change successed into adverb
  pkg/link-agent/controller.go
Labels: size/XS, approved, lgtm, ok-to-test

#44 feat: added node-controller and node adapter implementations
  go.mod
  pkg/apis/kosmos/v1alpha1/knode_types.go
  pkg/knode-manager/adapters/interface.go
  pkg/knode-manager/adapters/k8s/help.go
  pkg/knode-manager/adapters/k8s/node.go
  pkg/knode-manager/controllers/lease_controller.go
  pkg/knode-manager/controllers/node.go
  pkg/knode-manager/controllers/node_probe_controller.go
  pkg/knode-manager/knode.go
  pkg/knode-manager/utils/constants.go
  pkg/knode-manager/utils/conversion.go
  pkg/knode-manager/utils/k8s.go
  pkg/knode-manager/utils/lock/monitor.go
  pkg/knode-manager/utils/resources/node_resource.go
  pkg/knode-manager/utils/resources/resource.go
  pkg/knode-manager/utils/util.go
Labels: approved, lgtm, size/XXL

#47 add knode manager code owners
  cmd/knode-manager/OWNERS
  pkg/knode-manager/OWNERS
Labels: size/S, approved, lgtm

#46 feat: elevate adapter common configuration
  pkg/knode-manager/adapters/k8s/adapter_config.go
  pkg/knode-manager/adapters/k8s/node.go
  pkg/knode-manager/adapters/k8s/pod.go
  pkg/knode-manager/knode.go
Labels: approved, lgtm, size/L

#48 feat: Create the pod-adapter adn pod-controller in knode
  .gitignore
  cmd/knode-manager/app/config/config.go
  pkg/knode-manager/adapters/k8s/pod.go
  pkg/knode-manager/knode.go
Labels: approved, lgtm, size/L

#51 Add release stage on makefile and fix build tag no names bug
  Makefile
  hack/build.sh
  hack/docker.sh
  hack/release.sh
  hack/util.sh
Labels: size/M, approved, lgtm

#52 Add workflow pipeline for release
  .github/workflows/release.yml
Labels: size/M, approved, lgtm

#55 add release images stage
  .github/workflows/release_images.yml
  Makefile
Labels: size/S, approved, lgtm

#53 feat: add pv and pvc controller in knode
  pkg/knode-manager/adapters/interface.go
  pkg/knode-manager/adapters/k8s/adapter_config.go
  pkg/knode-manager/adapters/k8s/pv.go
  pkg/knode-manager/adapters/k8s/pvc.go
  pkg/knode-manager/controllers/pv.go
  pkg/knode-manager/controllers/pvc.go
  pkg/knode-manager/knode.go
  pkg/knode-manager/utils/constants.go
Labels: approved, lgtm, size/XL

#56 docs: add pull_request_template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/M, approved, lgtm

#59 fix: kosmosctl using issues
  Makefile
  deploy/clusterlink-agent.yaml
  deploy/clusterlink-controller-manager.yml
  deploy/clusterlink-elector.yml
  deploy/clusterlink-network-manager.yml
  deploy/clusterlink-operator.yml
  deploy/clusterlink-proxy.yml
  hack/util.sh
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/manifest/manifest_daemonsets.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/kosmosctl/unjoin/unjoin.go
  pkg/operator/addons/proxy/manifests.go
  pkg/operator/operator_controller.go
Labels: approved, lgtm, size/L

#67 Make knode be runnable
  pkg/knode-manager/adapters/k8s/node.go
  pkg/knode-manager/controllers/node.go
  pkg/knode-manager/controllers/pod.go
  pkg/knode-manager/knode.go
Labels: approved, lgtm, size/L

#61 Fix the scheduling module failed to start with an error indicating missing args and add deploy manifests
  Makefile
  cmd/scheduler/main.go
  deploy/clusterlink-agent-proxy-configmap.yml
  deploy/clusterlink-agent.yaml
  deploy/clusterlink-controller-manager.yml
  deploy/clusterlink-datapanel-rbac.yml
  deploy/clusterlink-elector-rbac.yml
  deploy/clusterlink-elector.yml
  deploy/clusterlink-namespace.yml
  deploy/clusterlink-network-manager.yml
  deploy/clusterlink-operator.yml
  deploy/clusterlink-proxy.yml
  deploy/scheduler/deployment.yaml
  deploy/scheduler/rbac.yaml
  go.mod
  hack/update-codegen.sh
  hack/util.sh
  pkg/apis/config/doc.go
  pkg/apis/config/register.go
  pkg/apis/config/scheme/scheme.go
  pkg/apis/config/types.go
  pkg/apis/config/v1beta1/defaults.go
  pkg/apis/config/v1beta1/doc.go
  pkg/apis/config/v1beta1/register.go
  pkg/apis/config/v1beta1/types.go
  pkg/apis/config/v1beta1/zz_generated.conversion.go
  pkg/apis/config/v1beta1/zz_generated.deepcopy.go
  pkg/apis/config/v1beta1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/scheduler/lifted/helpers/tainttoleration.go
  pkg/scheduler/lifted/plugins/knodevolumebinding/knode_volume_binding.go
Labels: approved, lgtm, size/XXL

#66 fix: floater https Certificate issue
  cmd/floater/app/floater.go
Labels: size/XS, approved, lgtm

#72 docs: update readme
  README.md
  README_zh.md
  docs/images/clusterlink-arch.png
  docs/images/knode-arch.png
  docs/images/link-arch.png
Labels: approved, lgtm, size/L

#68 fix: pv/pvc debug
  pkg/knode-manager/adapters/interface.go
  pkg/knode-manager/adapters/k8s/adapter_config.go
  pkg/knode-manager/adapters/k8s/pv.go
  pkg/knode-manager/adapters/k8s/pvc.go
  pkg/knode-manager/controllers/pv.go
  pkg/knode-manager/controllers/pvc.go
  pkg/knode-manager/controllers/pvpvc.go
  pkg/knode-manager/knode.go
  pkg/knode-manager/utils/constants.go
  pkg/knode-manager/utils/util.go
Labels: approved, lgtm, size/XXL

#75 fix knodevolumebinding plugins hasKnodeTaint for Reserve and Unreserve function
  deploy/scheduler/deployment.yaml
  pkg/scheduler/lifted/helpers/tainttoleration.go
  pkg/scheduler/lifted/plugins/knodetainttoleration/knode_tainttoleration.go
  pkg/scheduler/lifted/plugins/knodevolumebinding/knode_volume_binding.go
Labels: size/S, approved, lgtm

#78 fix: use master config to init resourcemanager for adapter
  .gitignore
  pkg/knode-manager/knode.go
Labels: size/M, approved, lgtm
