Repository kosmos-io/kosmos, pull requests merged in 2023-10, with the labels that each got.

#80 add MCS api schema
  go.mod
  go.sum
  pkg/scheme/scheme.go
  vendor/OWNERS
  vendor/github.com/imdario/mergo/.deepsource.toml
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/modules.txt
  vendor/sigs.k8s.io/mcs-api/LICENSE
  vendor/sigs.k8s.io/mcs-api/pkg/apis/v1alpha1/BUILD
  vendor/sigs.k8s.io/mcs-api/pkg/apis/v1alpha1/doc.go
  vendor/sigs.k8s.io/mcs-api/pkg/apis/v1alpha1/serviceexport.go
  vendor/sigs.k8s.io/mcs-api/pkg/apis/v1alpha1/serviceimport.go
  vendor/sigs.k8s.io/mcs-api/pkg/apis/v1alpha1/well_known_labels.go
  vendor/sigs.k8s.io/mcs-api/pkg/apis/v1alpha1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/mcs-api/pkg/apis/v1alpha1/zz_generated.register.go
Labels: approved, lgtm, size/XXL

#73 feat: Kosmosctl supports knode-manager module install and uninstall
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/kosmosctl.go
  pkg/kosmosctl/manifest/manifest_clusterrolebindings.go
  pkg/kosmosctl/manifest/manifest_clusterroles.go
  pkg/kosmosctl/manifest/manifest_crds.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/kosmosctl/manifest/manifest_serviceaccounts.go
  pkg/kosmosctl/uninstall/uninstall.go
  pkg/kosmosctl/util/builder.go
Labels: approved, lgtm, size/L

#71 Make clusterrouter deployable
  Makefile
  cmd/clustertree/OWNERS
  cmd/clustertree/knode-manager/app/config/config.go
  cmd/clustertree/knode-manager/app/manager.go
  cmd/clustertree/knode-manager/app/options/options.go
  cmd/clustertree/knode-manager/main.go
  deploy/clustertree-knode-controllers.yml
  hack/util.sh
  pkg/clustertree/OWNERS
  pkg/clustertree/knode-manager/adapters/interface.go
  pkg/clustertree/knode-manager/adapters/k8s/adapter_config.go
  pkg/clustertree/knode-manager/adapters/k8s/help.go
  pkg/clustertree/knode-manager/adapters/k8s/node.go
  pkg/clustertree/knode-manager/adapters/k8s/pod.go
  pkg/clustertree/knode-manager/controllers/lease_controller.go
  pkg/clustertree/knode-manager/controllers/node.go
  pkg/clustertree/knode-manager/controllers/node_probe_controller.go
  pkg/clustertree/knode-manager/controllers/pod.go
  pkg/clustertree/knode-manager/controllers/pvpvc.go
  pkg/clustertree/knode-manager/knode.go
  pkg/clustertree/knode-manager/knodemanager.go
  pkg/clustertree/knode-manager/result.go
  pkg/clustertree/knode-manager/utils/constants.go
  pkg/clustertree/knode-manager/utils/conversion.go
  pkg/clustertree/knode-manager/utils/expansion/expand.go
  pkg/clustertree/knode-manager/utils/k8s.go
  pkg/clustertree/knode-manager/utils/lock/monitor.go
  pkg/clustertree/knode-manager/utils/manager/resource.go
  pkg/clustertree/knode-manager/utils/podutils/env.go
  pkg/clustertree/knode-manager/utils/podutils/pod.go
  pkg/clustertree/knode-manager/utils/resources/node_resource.go
  pkg/clustertree/knode-manager/utils/resources/resource.go
  pkg/clustertree/knode-manager/utils/util.go
Labels: approved, lgtm, size/L

#88 feat: Kosmosctl supports knode join and unjoin
  examples/knode-demo.yaml
  pkg/kosmosctl/get/get.go
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/kosmosctl.go
  pkg/kosmosctl/manifest/manifest_clusterrolebindings.go
  pkg/kosmosctl/manifest/manifest_clusterroles.go
  pkg/kosmosctl/manifest/manifest_crds.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/kosmosctl/manifest/manifest_serviceaccounts.go
  pkg/kosmosctl/uninstall/uninstall.go
  pkg/kosmosctl/unjoin/unjoin.go
  pkg/kosmosctl/util/builder.go
  pkg/kosmosctl/util/check.go
Labels: approved, lgtm, size/XL

#92 fix: clustertree deploy yaml problem
  deploy/clustertree-knode-controllers.yml
  pkg/kosmosctl/manifest/manifest_deployments.go
Labels: size/XS, approved, lgtm

#86 add mcs crd
  deploy/crds/mcs/multicluster.x-k8s.io_serviceexports.yaml
  deploy/crds/mcs/multicluster.x-k8s.io_serviceimports.yaml
Labels: approved, lgtm, size/L

#94 fix: init event recorder
  pkg/clustertree/knode-manager/controllers/pod.go
  pkg/clustertree/knode-manager/controllers/pvpvc.go
Labels: size/S, approved, lgtm

#95 modify ci yml names
  .github/workflows/ci.yml
  .github/workflows/release_binaries.yml
  .github/workflows/sync_to_gitee.yaml
Labels: size/XS, approved, lgtm

#96 fix: Kosmosctl known issues
  deploy/clusterlink-operator.yml
  examples/cluster-demo.yaml
  pkg/clustertree/knode-manager/controllers/lease_controller.go
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/manifest/manifest_cr.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/kosmosctl/uninstall/uninstall.go
  pkg/kosmosctl/unjoin/unjoin.go
  pkg/kosmosctl/util/builder.go
Labels: approved, lgtm, size/L

#82 fix: host-network support
  pkg/clusterlink/network-manager/handlers/vxlocal_mac_cache.go
  pkg/clusterlink/network-manager/helpers/filter.go
Labels: approved, lgtm, size/L

#98 fix: Migrate clusterlink-system to kosmos-system
  cmd/clusterlink/elector/app/options/options.go
  cmd/clusterlink/network-manager/app/options/options.go
  cmd/clusterlink/operator/app/operator.go
  pkg/apis/kosmos/v1alpha1/cluster_types.go
  pkg/clusterlink/controllers/cluster/helper.go
  pkg/clusterlink/operator/addons/elector/manifests.go
  pkg/clusterlink/operator/addons/manager/manifests.go
  pkg/clusterlink/operator/addons/proxy/manifests.go
  pkg/kosmosctl/floater/doctor.go
  pkg/kosmosctl/get/get.go
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/manifest/manifest_cr.go
  pkg/kosmosctl/manifest/manifest_crds.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/kosmosctl/uninstall/uninstall.go
  pkg/kosmosctl/unjoin/unjoin.go
  pkg/kosmosctl/util/builder.go
  pkg/utils/constants.go
Labels: approved, lgtm, size/L

#107 fix: kosmosctl unjoin cluster issue
  pkg/kosmosctl/unjoin/unjoin.go
Labels: size/M, approved, lgtm

#112 feat: enable loose mode for flannel interface
  pkg/clusterlink/network/adapter.go
  pkg/clusterlink/network/constant.go
  pkg/clusterlink/network/env.go
Labels: size/M, approved, lgtm

#108 modify cluster_controller reconcile while cni is flannel
  pkg/clusterlink/controllers/cluster/cluster_controller.go
Labels: approved, lgtm, size/L

#115 fix: periodic update ARP table
  pkg/clusterlink/network/neigh.go
Labels: size/S, approved, lgtm

#116 fix member cluster's node controller can not clean orphan clusternode
  pkg/clusterlink/controllers/node/node_controller.go
Labels: size/S, approved, lgtm

#121 fix: Optimize kosmos install waiting process
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/uninstall/uninstall.go
  pkg/kosmosctl/unjoin/unjoin.go
  pkg/utils/constants.go
Labels: approved, lgtm, size/L

#97 add the mcs framework
  cmd/clustertree/knode-manager/app/manager.go
  pkg/clustertree/knode-manager/controllers/mcs/serviceexport_controller.go
  pkg/clustertree/knode-manager/controllers/mcs/serviceimport_controller.go
  pkg/clustertree/knode-manager/knode.go
  pkg/clustertree/knode-manager/knodemanager.go
  pkg/clustertree/knode-manager/utils/k8s.go
  pkg/scheme/scheme.go
  pkg/utils/helper/mcs.go
Labels: approved, lgtm, size/XXL

#124 fix: floater permission error
  cluster/images/buildx.floater.Dockerfile
  cluster/images/floater.Dockerfile
Labels: size/S, approved, lgtm

#129 fix: floater permission error
  cluster/images/buildx.floater.Dockerfile
  cluster/images/floater.Dockerfile
Labels: size/S, approved, lgtm

#130 fix: fix a bug for resource summary
  pkg/clustertree/knode-manager/adapters/k8s/node.go
Labels: size/XS, approved, lgtm

#126 fix: sync endpoint rather than endpointSlice
  pkg/clustertree/knode-manager/controllers/mcs/serviceexport_controller.go
  pkg/clustertree/knode-manager/controllers/mcs/serviceimport_controller.go
Labels: size/M, approved, lgtm

#132 feat: kosmosctl adds support for deploying CoreDNS
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/manifest/manifest_clusterrolebindings.go
  pkg/kosmosctl/manifest/manifest_clusterroles.go
  pkg/kosmosctl/manifest/manifest_configmaps.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/kosmosctl/manifest/manifest_serviceaccounts.go
  pkg/kosmosctl/manifest/manifest_services.go
  pkg/kosmosctl/uninstall/uninstall.go
  pkg/kosmosctl/util/builder.go
Labels: approved, lgtm, size/XL

#118 fix kosmos-scheduler miss lease permission
  deploy/scheduler/deployment.yaml
  deploy/scheduler/rbac.yaml
Labels: size/XS, approved, lgtm

#103 add kosmos-scheduler for kube-scheduler v1.26
  Makefile
  cmd/scheduler/main.go
  deploy/scheduler/deployment.yaml
  deploy/scheduler/rbac.yaml
  hack/update-codegen.sh
  hack/util.sh
  pkg/apis/config/doc.go
  pkg/apis/config/register.go
  pkg/apis/config/scheme/scheme.go
  pkg/apis/config/types.go
  pkg/apis/config/v1/defaults.go
  pkg/apis/config/v1/doc.go
  pkg/apis/config/v1/register.go
  pkg/apis/config/v1/types.go
  pkg/apis/config/v1/zz_generated.conversion.go
  pkg/apis/config/v1/zz_generated.deepcopy.go
  pkg/apis/config/v1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/scheduler/lifted/helpers/tainttoleration.go
  pkg/scheduler/lifted/plugins/knodetainttoleration/knode_tainttoleration.go
  pkg/scheduler/lifted/plugins/knodevolumebinding/knode_volume_binding.go
Labels: approved, lgtm, size/XXL

#136 docs: update contributors image
  README.md
  README_zh.md
Labels: size/XS, approved, lgtm

#137 fix: sync all endpoint address in serviceImport
  pkg/clustertree/knode-manager/controllers/mcs/serviceimport_controller.go
  pkg/utils/helper/mcs.go
Labels: approved, lgtm, size/L

#138 modify kosmos go package
  hack/build.sh
  hack/release.sh
  hack/util.sh
Labels: size/XS, approved, lgtm

#140 feat: init cluster manager framework
  Makefile
  cmd/clustertree/cluster-manager/app/manager.go
  cmd/clustertree/cluster-manager/app/options/options.go
  cmd/clustertree/cluster-manager/app/options/validation.go
  cmd/clustertree/cluster-manager/main.go
  cmd/clustertree/knode-manager/app/config/config.go
  cmd/clustertree/knode-manager/app/extension_apps.go
  cmd/clustertree/knode-manager/app/manager.go
  cmd/clustertree/knode-manager/app/options/options.go
  deploy/clustertree-knode-controllers.yml
  hack/util.sh
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
  pkg/clustertree/cluster-manager/extensions/daemonset/constants.go
  pkg/clustertree/cluster-manager/extensions/daemonset/daemonset_controller.go
  pkg/clustertree/cluster-manager/extensions/daemonset/daemonset_mirror_controller.go
  pkg/clustertree/cluster-manager/extensions/daemonset/distribute_controller.go
  pkg/clustertree/cluster-manager/extensions/daemonset/host_daemon_controller.go
  pkg/clustertree/cluster-manager/extensions/daemonset/update.go
  pkg/clustertree/cluster-manager/extensions/daemonset/utils.go
  pkg/clustertree/cluster-manager/utils/util.go
  pkg/clustertree/knode-manager/knode.go
  pkg/clustertree/knode-manager/knodemanager.go
  pkg/clustertree/knode-manager/result.go
  pkg/clustertree/knode-manager/utils/util.go
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/manifest/manifest_clusterrolebindings.go
  pkg/kosmosctl/manifest/manifest_clusterroles.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/kosmosctl/manifest/manifest_serviceaccounts.go
Labels: approved, lgtm, size/XXL

#147 feat: init pod controllers
  cmd/clustertree/cluster-manager/app/manager.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/leaf_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/utils/constants.go
  pkg/utils/pod.go
Labels: approved, lgtm, size/XXL

#144 Fix comment
  pkg/clustertree/knode-manager/controllers/mcs/serviceimport_controller.go
Labels: size/XS, approved, lgtm

#157 fix: fix the kosmos deploy yaml error
  deploy/scheduler/deployment.yaml
  deploy/scheduler/rbac.yaml
Labels: size/XS, approved, lgtm

#155 docs: Modified pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/S, approved, lgtm

#159 feat: synchronize configmap and secret to sub clusters
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/leaf_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/sync_resources_controller.go
  pkg/utils/k8s.go
Labels: approved, lgtm, size/L

#162 feat: do not create a pod with the label [daemonset.kosmos.io/managed…
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
Labels: size/XS, approved, lgtm

#134 fix: uninstall return error
  pkg/kosmosctl/uninstall/uninstall.go
Labels: approved, lgtm, size/L

#149 feat: delete https certificate file
  cluster/images/buildx.floater.Dockerfile
  cluster/images/floater.Dockerfile
  cmd/clusterlink/floater/app/floater.go
  cmd/clusterlink/floater/certificate/file.crt
  cmd/clusterlink/floater/certificate/file.key
  hack/build.sh
Labels: approved, lgtm, size/L

#164 keep interface implements and interface consistent
  pkg/utils/controllers/controller_util.go
  pkg/utils/controllers/controller_util_test.go
Labels: size/M, approved, lgtm

#166 feat: node controllers
  cmd/clustertree/cluster-manager/app/manager.go
  cmd/clustertree/cluster-manager/app/options/options.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/node_lease_controller.go
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
  pkg/clustertree/cluster-manager/controllers/serviceimport_controller.go
  pkg/utils/node.go
  pkg/utils/resources.go
Labels: approved, lgtm, size/XL

#152 add pod reflect controller
  cmd/clustertree/cluster-manager/app/extersion_apps.go
  cmd/clustertree/cluster-manager/app/manager.go
  pkg/clustertree/cluster-manager/extensions/daemonset/constants.go
  pkg/clustertree/cluster-manager/extensions/daemonset/daemonset_controller.go
  pkg/clustertree/cluster-manager/extensions/daemonset/daemonset_mirror_controller.go
  pkg/clustertree/cluster-manager/extensions/daemonset/distribute_controller.go
  pkg/clustertree/cluster-manager/extensions/daemonset/host_daemon_controller.go
  pkg/clustertree/cluster-manager/extensions/daemonset/pod_reflect_controller.go
Labels: approved, lgtm, size/XL

#141 add an English readme
  README.md
  docs/images/kosmos-WechatIMG.jpg
Labels: size/M, approved, lgtm

#167 add Chinese and English readme quick link
  README.md
  README_zh.md
Labels: size/XS, approved, lgtm

#101 title: Add import and export subcommand for kosmosctl
  pkg/kosmosctl/kosmosctl.go
  pkg/kosmosctl/rsmigrate/common.go
  pkg/kosmosctl/rsmigrate/options.go
  pkg/kosmosctl/rsmigrate/serviceexport.go
  pkg/kosmosctl/rsmigrate/serviceimport.go
Labels: approved, lgtm, size/L

#168 fix: make mcs runnable
  cmd/clustertree/cluster-manager/app/manager.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/serviceexport_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/serviceimport_controller.go
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
  pkg/utils/k8s.go
  pkg/utils/node_client.go
Labels: approved, lgtm, size/L

#169 add pv pvc controller
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/leaf_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/root_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/leaf_pvc_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/root_pvc_controller.go
  pkg/utils/pvpvc.go
Labels: approved, lgtm, size/XL

#171 fix pvpvc nil pointer issues
  pkg/clustertree/cluster-manager/controllers/pv/leaf_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/root_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/leaf_pvc_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/root_pvc_controller.go
Labels: size/S, approved, lgtm

#170 feat: Synchronize the pod environment variables of the main cluster t…
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/common_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/leaf_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/leaf_pvc_controller.go
  pkg/utils/constants.go
  pkg/utils/k8s.go
  pkg/utils/podutils/env.go
  pkg/utils/podutils/pod.go
Labels: approved, lgtm, size/XXL

#173 refact: init podcontroller and synccontroller in root manager
  cmd/clustertree/cluster-manager/app/manager.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/common_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/leaf_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/utils/leaf_resource_manager.go
  pkg/utils/constants.go
  pkg/utils/k8s.go
Labels: approved, lgtm, size/XL

#174 feat: Debugging the creation and deletion of pods with configmap
  pkg/clustertree/cluster-manager/controllers/common_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/leaf_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/utils/leaf_resource_manager.go
  pkg/utils/k8s.go
Labels: approved, lgtm, size/L

#175 new style for pv pvc
  cmd/clustertree/cluster-manager/app/manager.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/leaf_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/root_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/leaf_pvc_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/root_pvc_controller.go
  pkg/clustertree/cluster-manager/utils/leaf_resource_manager.go
Labels: approved, lgtm, size/L

#176 fix: add coredns convertor
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
Labels: size/M, approved, lgtm

#177 fix: env bug for fieldRef
  pkg/utils/podutils/env.go
Labels: size/S, approved, lgtm

#178 fix: clustertree bugs
  cmd/clustertree/cluster-manager/app/manager.go
  cmd/clustertree/cluster-manager/app/options/options.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/leaf_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/leaf_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/root_pv_controller.go
  pkg/utils/constants.go
  pkg/utils/k8s.go
  pkg/utils/node.go
Labels: approved, lgtm, size/L

#179 fix:leaf pvc can't be deleted
  pkg/clustertree/cluster-manager/controllers/pv/leaf_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/root_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/leaf_pvc_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/root_pvc_controller.go
  pkg/utils/k8s.go
Labels: size/S, approved, lgtm

#181 fix: pv claimRef bug
  pkg/clustertree/cluster-manager/controllers/node_lease_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/leaf_pv_controller.go
Labels: size/XS, approved, lgtm

#182 feat: Out of sync daemon set pod
  pkg/clustertree/cluster-manager/controllers/common_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/leaf_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/utils/leaf_resource_manager.go
Labels: size/M, approved, lgtm

#180 fix: fix the client usage in mcs
  cmd/clustertree/cluster-manager/app/manager.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/serviceimport_controller.go
  pkg/kosmosctl/rsmigrate/common.go
  pkg/kosmosctl/rsmigrate/options.go
  pkg/utils/resource_manager.go
Labels: size/M, approved, lgtm

#187 fix:deal with the same name root pv
  pkg/clustertree/cluster-manager/controllers/pv/leaf_pv_controller.go
Labels: size/XS, approved, lgtm
