Repository kosmos-io/kosmos, pull requests merged in 2023-12, with the labels that each got.

#312 fix: add daemonset filter
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/utils/rootcluster.go
Labels: size/XS, approved, lgtm, kind/bug

#313 fix: add VtepDevIndex param for vxlan
  pkg/clusterlink/network/device.go
Labels: size/M, approved, lgtm, kind/bug

#310 feat: support find cilium cluster ip cidr
  go.mod
  go.sum
  pkg/clusterlink/controllers/cluster/cluster_controller.go
  vendor/github.com/klauspost/compress/fse/README.md
  vendor/github.com/klauspost/compress/huff0/README.md
  vendor/github.com/pelletier/go-toml/example-crlf.toml
  vendor/github.com/spf13/cast/.gitignore
  vendor/github.com/spf13/cast/LICENSE
  vendor/github.com/spf13/cast/Makefile
  vendor/github.com/spf13/cast/README.md
  vendor/github.com/spf13/cast/cast.go
  vendor/github.com/spf13/cast/caste.go
  vendor/github.com/spf13/cast/timeformattype_string.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, kind/feature

#316 feat: Add e2e approvers and uncomment some testcase
  hack/OWNERS
  hack/rune2e.sh
  test/OWNERS
Labels: size/S, approved, lgtm, kind/cleanup

#287 feature: support one-to-many model for the leaf node feature
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/node_lease_controller.go
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/utils/leaf_model_handler.go
  pkg/clustertree/cluster-manager/utils/leaf_resource_manager.go
  pkg/utils/podutils/pod.go
  pkg/utils/resources.go
  test/e2e/elector_test.go
  test/e2e/framework/cluster.go
  test/e2e/framework/deployment_sample.go
  test/e2e/leaf_node_test.go
  test/e2e/suit_test.go
Labels: approved, lgtm, size/XXL, kind/feature

#318 fix: delete the daemonset pod on root that is assigned to the leaf node
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
Labels: size/XS, approved, lgtm, kind/bug

#319 feat: auto detect interface name
  deploy/clusterlink-agent.yaml
  deploy/crds/kosmos.io_clusters.yaml
  pkg/apis/kosmos/v1alpha1/cluster_types.go
  pkg/clusterlink/agent-manager/auto_detect_controller.go
  pkg/clusterlink/controllers/node/node_controller.go
  pkg/operator/clusterlink/agent/manifests.go
  pkg/utils/lifted/autodetection/filtered.go
  pkg/utils/lifted/autodetection/interfaces.go
  pkg/utils/lifted/autodetection/reachaddr.go
Labels: approved, lgtm, size/L, kind/feature

#315 feat: support setting iptables mode
  go.mod
  go.sum
  pkg/clusterlink/network/iptables/iptables.go
  vendor/github.com/coreos/go-iptables/iptables/iptables.go
  vendor/modules.txt
Labels: size/M, approved, lgtm, kind/bug

#323 docs: Update the WeChat QR code
  README.md
  docs/images/kosmos-WeChatIMG.png
  docs/images/kosmos-WechatIMG.jpg
Labels: kind/docs, size/XS, approved, lgtm

#331 cherry-pick bug fixs to release-0.2.0
  go.mod
  go.sum
  pkg/clusterlink/network/device.go
  pkg/clusterlink/network/iptables/iptables.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/utils/rootcluster.go
  vendor/github.com/coreos/go-iptables/iptables/iptables.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, kind/bug

#332 feat: periodic check of environmental variables
  pkg/clusterlink/network/env.go
Labels: size/M, approved, lgtm, kind/feature

#333 feat: periodic check of environmental variables
  pkg/clusterlink/network/env.go
Labels: size/M, approved, lgtm

#327 Add informer factory and gvr register
  pkg/utils/informers/InformerFactory.go
Labels: approved, lgtm, size/L, kind/feature

#325 feat: make kosmosctl support --context and support e2e test for kosmosctl
  hack/cluster.sh
  hack/prepare-e2e.sh
  pkg/kosmosctl/floater/analysis.go
  pkg/kosmosctl/floater/check.go
  pkg/kosmosctl/floater/floater.go
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/kosmosctl.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/kosmosctl/rsmigrate/options.go
  pkg/kosmosctl/rsmigrate/serviceexport.go
  pkg/kosmosctl/rsmigrate/serviceimport.go
  pkg/kosmosctl/uninstall/uninstall.go
  pkg/kosmosctl/unjoin/unjoin.go
  pkg/utils/k8s.go
  pkg/utils/kube_client.go
  pkg/utils/node_client.go
  test/e2e/deploy/cr/cluster-cr.yaml
  test/e2e/deploy/nginx/nginx.yaml
  test/e2e/leaf_node_test.go
Labels: size/XL, kind/feature

#336 fix: modify knode to leafnode for kosmos-scheduler plugins
  cmd/scheduler/main.go
  deploy/scheduler/deployment.yaml
  pkg/apis/config/register.go
  pkg/apis/config/types.go
  pkg/apis/config/v1beta1/defaults.go
  pkg/apis/config/v1beta1/leafnodedistributionargs_types.go
  pkg/apis/config/v1beta1/leafnodevolumebinding_types.go
  pkg/apis/config/v1beta1/register.go
  pkg/apis/config/v1beta1/zz_generated.conversion.go
  pkg/apis/config/v1beta1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/scheduler/lifted/helpers/tainttoleration.go
  pkg/scheduler/lifted/plugins/leafnodetainttoleration/leafnode_tainttoleration.go
  pkg/scheduler/lifted/plugins/leafnodevolumebinding/leafnode_volume_binding.go
Labels: lgtm, size/L, kind/bug

#337 fix: modify knode to leafnode for kosmos-scheduler(v1.26.3) plugins
  cmd/scheduler/main.go
  deploy/scheduler/deployment.yaml
  pkg/apis/config/register.go
  pkg/apis/config/types.go
  pkg/apis/config/v1/defaults.go
  pkg/apis/config/v1/register.go
  pkg/apis/config/v1/types.go
  pkg/apis/config/v1/zz_generated.conversion.go
  pkg/apis/config/v1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/scheduler/lifted/helpers/tainttoleration.go
  pkg/scheduler/lifted/plugins/leafnodetainttoleration/knode_tainttoleration.go
  pkg/scheduler/lifted/plugins/leafnodevolumebinding/leafnode_volume_binding.go
Labels: size/L, kind/bug

#334 Add finalizer for mcs
  cmd/clustertree/cluster-manager/app/manager.go
  cmd/clustertree/cluster-manager/app/options/options.go
  hack/cluster.sh
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/auto_mcs_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/serviceexport_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/serviceimport_controller.go
  pkg/utils/constants.go
  pkg/utils/flags/backoffflag.go
  test/e2e/leaf_node_test.go
Labels: size/L
