Repository kosmos-io/kosmos, pull requests merged in 2023-11, with the labels that each got.

#188 feat: update cluster crd
  deploy/crds/kosmos.io_clusters.yaml
  deploy/crds/kosmos.io_knodes.yaml
  pkg/apis/kosmos/v1alpha1/cluster_types.go
  pkg/apis/kosmos/v1alpha1/knode_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/clusterlink/controllers/calicoippool/calicoippool_controller.go
  pkg/clusterlink/controllers/cluster/cluster_controller.go
  pkg/clusterlink/controllers/node/node_controller.go
  pkg/clusterlink/controllers/nodecidr/nodecidr_controller.go
  pkg/clusterlink/network-manager/handlers/globalmap.go
  pkg/clusterlink/network-manager/handlers/host_network.go
  pkg/clusterlink/network-manager/handlers/pod_routes.go
  pkg/clusterlink/network-manager/handlers/svc_routes.go
  pkg/clusterlink/network-manager/handlers/vxbridge_network.go
  pkg/clusterlink/network-manager/handlers/vxlocal_network.go
  pkg/clusterlink/network-manager/helpers/filter.go
  pkg/clusterlink/network/adapter.go
  pkg/clusterlink/operator/addons/option/option.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, lgtm, size/XL

#183 feat: Add single cluster network connectivity visual analysis
  cluster/images/buildx.floater.Dockerfile
  cluster/images/floater.Dockerfile
  cmd/clusterlink/floater/app/floater.go
  cmd/clusterlink/operator/app/operator.go
  pkg/clusterlink/agent/controller.go
  pkg/clusterlink/network/interface.go
  pkg/kosmosctl/floater/analysis.go
  pkg/kosmosctl/floater/check.go
  pkg/kosmosctl/floater/floater.go
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/kosmosctl.go
  pkg/kosmosctl/manifest/manifest_cr.go
  pkg/kosmosctl/manifest/manifest_daemonsets.go
  pkg/kosmosctl/uninstall/uninstall.go
  pkg/kosmosctl/unjoin/unjoin.go
  pkg/kosmosctl/util/verify.go
  pkg/utils/constants.go
Labels: approved, lgtm, size/XL

#189 fix: clusterlink ignore kosmos nodes
  deploy/clustertree-cluster-manager.yml
  deploy/clustertree-knode-controllers.yml
  pkg/clusterlink/controllers/node/node_controller.go
  pkg/utils/k8s.go
Labels: approved, lgtm, size/L

#190 Add leaf node generate rules
  deploy/crds/kosmos.io_clusters.yaml
  docs/proposals/leafnodegenerate/README.md
  docs/proposals/leafnodegenerate/img/leaf-nodes.png
  hack/update-crds.sh
  pkg/apis/kosmos/v1alpha1/cluster_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, lgtm, size/L

#191 modify pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/docs, size/S, approved, lgtm

#193 fix: fix the member cluster serviceimport nodeport error
  pkg/clustertree/cluster-manager/controllers/mcs/serviceexport_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/serviceimport_controller.go
Labels: size/M, approved, lgtm, kind/bug

#194 Adaptation of a modified clusterCRD
  cmd/clustertree/cluster-manager/app/extersion_apps.go
  deploy/crds/kosmos.io_shadowdaemonsets.yaml
  hack/generate/generate.go
  pkg/apis/kosmos/v1alpha1/daemonset_types.go
  pkg/clustertree/cluster-manager/extensions/daemonset/daemonset_controller.go
  pkg/clustertree/cluster-manager/extensions/daemonset/distribute_controller.go
  pkg/clustertree/cluster-manager/extensions/daemonset/pod_reflect_controller.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/kosmosctl/manifest/manifest_crds.go
Labels: approved, lgtm, size/XXL, kind/feature

#195 modify leaf_resource_manager to singleton
  cmd/clustertree/cluster-manager/app/manager.go
  pkg/clustertree/cluster-manager/utils/leaf_resource_manager.go
Labels: size/S, approved, lgtm, kind/cleanup

#197 fix:leaf pvc with wrong selected-node
  pkg/clustertree/cluster-manager/controllers/pvc/root_pvc_controller.go
Labels: size/XS, approved, lgtm, kind/bug

#198 fix: pod controller create pvc with wrong selected-node
  pkg/utils/podutils/pod.go
Labels: size/XS, approved, lgtm, kind/bug

#199 feat: auto create mcs resource for some service
  cmd/clustertree/cluster-manager/app/manager.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/auto_mcs_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/serviceexport_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/serviceimport_controller.go
  pkg/clustertree/cluster-manager/utils/leaf_resource_manager.go
  pkg/clustertree/cluster-manager/utils/rootcluster.go
  pkg/utils/constants.go
  pkg/utils/node_client.go
Labels: approved, lgtm, size/L, kind/feature

#200 fix: support change kosmos.io/auto-create-mcs value
  pkg/clustertree/cluster-manager/controllers/mcs/auto_mcs_controller.go
Labels: size/S, approved, lgtm, kind/bug

#202 fix:wrong rv from leaf pvc
  pkg/clustertree/cluster-manager/controllers/pvc/leaf_pvc_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/root_pvc_controller.go
  pkg/utils/podutils/pod.go
Labels: size/S, approved, lgtm

#203 feat: supports specifying coredns through configuration
  cmd/clustertree/cluster-manager/app/options/options.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
Labels: size/S, approved, lgtm, kind/feature

#192 feat: operator relocation transformation
  Makefile
  cmd/operator/app/operator.go
  cmd/operator/app/options/options.go
  cmd/operator/app/options/validation.go
  cmd/operator/main.go
  hack/util.sh
  pkg/kosmosctl/floater/analysis.go
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/manifest/manifest_clusterrolebindings.go
  pkg/kosmosctl/manifest/manifest_clusterroles.go
  pkg/kosmosctl/manifest/manifest_cr.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/kosmosctl/manifest/manifest_serviceaccounts.go
  pkg/kosmosctl/uninstall/uninstall.go
  pkg/kosmosctl/unjoin/unjoin.go
  pkg/operator/clusterlink/agent/agent.go
  pkg/operator/clusterlink/agent/manifests.go
  pkg/operator/clusterlink/elector/elector.go
  pkg/operator/clusterlink/elector/manifests.go
  pkg/operator/clusterlink/global/global.go
  pkg/operator/clusterlink/global/manifests.go
  pkg/operator/clusterlink/install.go
  pkg/operator/clusterlink/manager/manager.go
  pkg/operator/clusterlink/manager/manifests.go
  pkg/operator/clusterlink/option/option.go
  pkg/operator/clusterlink/proxy/manifests.go
  pkg/operator/clusterlink/proxy/proxy.go
  pkg/operator/clusterlink/utils/idempotency.go
  pkg/operator/clusterlink/utils/template.go
  pkg/operator/operator_controller.go
  pkg/utils/constants.go
Labels: approved, lgtm, size/XXL, kind/feature

#205 fix:root pvc should be without no selected-node
  pkg/clustertree/cluster-manager/controllers/pvc/leaf_pvc_controller.go
Labels: size/XS, approved, lgtm, kind/bug

#206 fix: fix pvc updated error
  pkg/scheduler/lifted/plugins/knodevolumebinding/knode_volume_binding.go
Labels: size/S, approved, lgtm, kind/bug

#209 fix: Remove node related logic
  deploy/crds/kosmos.io_knodes.yaml
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/manifest/manifest_crds.go
  pkg/kosmosctl/uninstall/uninstall.go
  pkg/operator/operator_controller.go
  pkg/utils/constants.go
Labels: approved, lgtm, size/XXL, kind/cleanup

#207 cherry-pick manually[fix pvc create error]
  deploy/scheduler/deployment.yaml
  deploy/scheduler/rbac.yaml
  pkg/scheduler/lifted/plugins/knodevolumebinding/knode_volume_binding.go
Labels: size/M, approved, lgtm, kind/bug

#211 fix: fix scheduler bug
  pkg/scheduler/lifted/plugins/knodevolumebinding/knode_volume_binding.go
Labels: size/XS, approved, lgtm

#212 fix scheduler pvc create bug error
  pkg/scheduler/lifted/plugins/knodevolumebinding/knode_volume_binding.go
Labels: size/XS, approved, lgtm, kind/bug

#216 fix: null pointer exception when creating routes
  deploy/clusterlink-network-manager.yml
  pkg/clusterlink/network-manager/handlers/pod_routes.go
  pkg/clusterlink/network-manager/handlers/svc_routes.go
Labels: size/M, approved, lgtm, kind/bug

#218 fix: nil point exception when create cluster
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/manifest/manifest_deployments.go
Labels: size/M, approved, lgtm, kind/bug

#220 modify leaf mod and add node name
  pkg/apis/kosmos/v1alpha1/cluster_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: size/M, approved, lgtm, kind/feature

#221 Impl leaf model
  deploy/crds/kosmos.io_clusters.yaml
  deploy/crds/kosmos.io_knodes.yaml
  pkg/apis/kosmos/v1alpha1/cluster_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/node_lease_controller.go
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, lgtm, size/L, kind/feature

#227 feature: support leaf model feature
  deploy/crds/kosmos.io_clusters.yaml
  go.mod
  go.sum
  pkg/apis/kosmos/v1alpha1/cluster_types.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/node_lease_controller.go
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/utils/constants.go
  pkg/utils/k8s.go
  vendor/github.com/mattbaird/jsonpatch/.gitignore
  vendor/github.com/mattbaird/jsonpatch/LICENSE
  vendor/github.com/mattbaird/jsonpatch/README.md
  vendor/github.com/mattbaird/jsonpatch/jsonpatch.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/yaml/meta.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/yaml/yaml.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, kind/feature

#226 feat: support single node model
  .gitignore
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/common_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/auto_mcs_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/storage_handler.go
  pkg/clustertree/cluster-manager/controllers/pv/root_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/root_pvc_controller.go
  pkg/clustertree/cluster-manager/utils/leaf_resource_manager.go
  pkg/utils/podutils/pod.go
Labels: approved, lgtm, size/L, kind/feature

#229 Clustertree zyx 12
  cmd/clustertree/cluster-manager/app/manager.go
  cmd/clustertree/cluster-manager/app/options/options.go
  cmd/clustertree/cluster-manager/main.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/common_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/storage_handler.go
  pkg/clustertree/cluster-manager/controllers/pv/root_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/root_pvc_controller.go
  pkg/clustertree/cluster-manager/utils/leaf_resource_manager.go
  pkg/utils/constants.go
Labels: approved, lgtm, size/L, kind/feature

#228 feature: support leaf model feature
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/node_lease_controller.go
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
  pkg/utils/constants.go
Labels: approved, lgtm, size/L, kind/feature

#230 fix: pv and pvc annotations duplicated error
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/leaf_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/leaf_pvc_controller.go
Labels: size/M, approved, lgtm, kind/bug

#231 feat: allow some daemonset pod
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/utils/constants.go
Labels: size/XS, approved, lgtm, kind/feature

#224 feat: add address for knode
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
  pkg/clustertree/cluster-manager/utils/rootcluster.go
Labels: approved, lgtm, size/L, kind/feature

#232 fix: skip sync image pull secret
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
Labels: size/XS, approved, lgtm, kind/bug

#233 feat: allow all daemonset
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
Labels: size/XS, approved, lgtm, kind/feature

#213 fix: Automation Script Modification
  deploy/clusterlink-agent-proxy-configmap.yml
  deploy/clusterlink-agent.yaml
  deploy/clusterlink-controller-manager.yml
  deploy/clusterlink-datapanel-rbac.yml
  deploy/clusterlink-elector-rbac.yml
  deploy/clusterlink-elector.yml
  deploy/clusterlink-namespace.yml
  deploy/clusterlink-network-manager.yml
  deploy/clusterlink-operator.yml
  deploy/clusterlink-proxy.yml
  hack/cluster.sh
  hack/local-up-clusterlink.sh
Labels: approved, lgtm, size/L, kind/bug

#235 reactor: reactor the code of leafModel
  cmd/clustertree/cluster-manager/app/manager.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/auto_mcs_controller.go
  pkg/clustertree/cluster-manager/controllers/node_lease_controller.go
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
  pkg/clustertree/cluster-manager/utils/leaf_model_handler.go
  pkg/clustertree/cluster-manager/utils/leaf_resource_manager.go
  pkg/clustertree/cluster-manager/utils/rootcluster.go
Labels: approved, lgtm, size/XL, kind/cleanup

#242 fix: fix potential bug
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
Labels: size/XS, approved, lgtm, kind/bug

#245 fix: sync ca from root cluster
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
Labels: size/XS, approved, lgtm, kind/bug

#246 Modify Readme markdown
  README.md
  README_zh.md
  docs/images/clustertree-arch.png
Labels: kind/docs, size/M, approved, lgtm

#249 feat: support exec and logs
  cmd/clustertree/cluster-manager/app/manager.go
  cmd/clustertree/cluster-manager/app/options/options.go
  deploy/clustertree-cluster-manager.yml
  go.mod
  go.sum
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
  pkg/clustertree/cluster-manager/node-server/api/errdefs/invalid.go
  pkg/clustertree/cluster-manager/node-server/api/errdefs/notfound.go
  pkg/clustertree/cluster-manager/node-server/api/errdefs/wrapped.go
  pkg/clustertree/cluster-manager/node-server/api/exec.go
  pkg/clustertree/cluster-manager/node-server/api/helper.go
  pkg/clustertree/cluster-manager/node-server/api/logs.go
  pkg/clustertree/cluster-manager/node-server/api/remotecommand/attach.go
  pkg/clustertree/cluster-manager/node-server/api/remotecommand/exec.go
  pkg/clustertree/cluster-manager/node-server/api/remotecommand/httpstream.go
  pkg/clustertree/cluster-manager/node-server/api/remotecommand/websocket.go
  pkg/clustertree/cluster-manager/node-server/server.go
  pkg/clustertree/cluster-manager/utils/leaf_model_handler.go
  pkg/clustertree/cluster-manager/utils/leaf_resource_manager.go
  pkg/clustertree/cluster-manager/utils/rootcluster.go
  pkg/utils/podutils/env.go
  vendor/github.com/gorilla/mux/.editorconfig
  vendor/github.com/gorilla/mux/.gitignore
  vendor/github.com/gorilla/mux/LICENSE
  vendor/github.com/gorilla/mux/Makefile
  vendor/github.com/gorilla/mux/README.md
  vendor/github.com/gorilla/mux/doc.go
  vendor/github.com/gorilla/mux/middleware.go
  vendor/github.com/gorilla/mux/mux.go
  vendor/github.com/gorilla/mux/regexp.go
  vendor/github.com/gorilla/mux/route.go
  vendor/github.com/gorilla/mux/test_helpers.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, kind/feature

#254 modify clustertree-arch
  docs/images/clustertree-arch.png
Labels: kind/docs, approved, lgtm

#255 modify clustertree arch png and notes
  docs/images/clustertree-arch.png
Labels: size/XS, approved, lgtm, kind/cleanup

#252 fix:1.root pvc could be lost possibly; 2.leaf pvc spec could not be m…
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/leaf_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/leaf_pvc_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/root_pvc_controller.go
  pkg/utils/pvpvc.go
Labels: size/M, approved, lgtm, kind/bug

#253 Fix nodenotfound err
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/utils/leaf_model_handler.go
Labels: size/M, approved, lgtm, kind/bug

#244 fix: fix ipfamily mismatch in root cluster and leaf cluster
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/serviceexport_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/serviceimport_controller.go
Labels: size/M, approved, lgtm, kind/bug

#257 fix: kctl incorrect image repository
  pkg/kosmosctl/floater/check.go
  pkg/kosmosctl/floater/floater.go
Labels: size/S, approved, lgtm, kind/bug

#248 feat: support exec and logs
  cmd/clustertree/cluster-manager/app/manager.go
  deploy/clustertree-cluster-manager.yml
  go.mod
  go.sum
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
  pkg/clustertree/cluster-manager/node-server/api/errdefs.go
  pkg/clustertree/cluster-manager/node-server/api/exec.go
  pkg/clustertree/cluster-manager/node-server/api/helper.go
  pkg/clustertree/cluster-manager/node-server/api/logs.go
  pkg/clustertree/cluster-manager/node-server/api/remotecommand/attach.go
  pkg/clustertree/cluster-manager/node-server/api/remotecommand/exec.go
  pkg/clustertree/cluster-manager/node-server/api/remotecommand/httpstream.go
  pkg/clustertree/cluster-manager/node-server/api/remotecommand/websocket.go
  pkg/clustertree/cluster-manager/node-server/server.go
  pkg/clustertree/cluster-manager/utils/leaf_model_handler.go
  pkg/clustertree/cluster-manager/utils/leaf_resource_manager.go
  pkg/clustertree/cluster-manager/utils/rootcluster.go
  pkg/utils/podutils/env.go
  vendor/github.com/gorilla/mux/.editorconfig
  vendor/github.com/gorilla/mux/.gitignore
  vendor/github.com/gorilla/mux/LICENSE
  vendor/github.com/gorilla/mux/Makefile
  vendor/github.com/gorilla/mux/README.md
  vendor/github.com/gorilla/mux/doc.go
  vendor/github.com/gorilla/mux/middleware.go
  vendor/github.com/gorilla/mux/mux.go
  vendor/github.com/gorilla/mux/regexp.go
  vendor/github.com/gorilla/mux/route.go
  vendor/github.com/gorilla/mux/test_helpers.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, kind/feature

#256 fix: TopologySpreadConstraints cause the leaf pod pending
  pkg/utils/k8s.go
  pkg/utils/podutils/pod.go
Labels: size/XS, approved, lgtm, kind/bug

#258 fix: nested env sequence problem
  pkg/utils/podutils/env.go
  pkg/utils/podutils/expand.go
Labels: approved, lgtm, size/L, kind/bug

#239 E2E: Integrate end-to-end workflows
  .github/workflows/e2e.yml
Labels: size/S, approved, lgtm, kind/e2e

#261 feat: add storage oneway controllers
  cmd/clustertree/cluster-manager/app/manager.go
  cmd/clustertree/cluster-manager/app/options/options.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/oneway_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/oneway_pvc_controller.go
  pkg/utils/pvpvc.go
Labels: approved, lgtm, size/L, kind/feature

#264 fix: the pod with a custom scheduler cannot be started
  pkg/clustertree/cluster-manager/controllers/common_controller.go
  pkg/utils/constants.go
  pkg/utils/podutils/pod.go
Labels: size/XS, approved, lgtm, kind/bug

#251 feat: Script supports installing kind and kubectl
  deploy/clustertree-cluster-manager.yml
  hack/cluster.sh
  hack/install-go.sh
  hack/install_kind_kubectl.sh
  hack/local-up-clusterlink.sh
  hack/rune2e.sh
Labels: approved, lgtm, size/L, kind/feature

#265 docs: compress pictures
  docs/images/clustertree-arch.png
  docs/images/link-arch.png
Labels: kind/docs, size/XS, approved, lgtm

#266 fix: fix the clusterName in leafResourceManger not consistent
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/auto_mcs_controller.go
  pkg/clustertree/cluster-manager/utils/leaf_resource_manager.go
Labels: size/S, approved, lgtm, kind/bug

#260 feat: support auto create mcs with flags
  cmd/clustertree/cluster-manager/app/manager.go
  cmd/clustertree/cluster-manager/app/options/options.go
  pkg/clustertree/cluster-manager/controllers/mcs/auto_mcs_controller.go
Labels: size/M, approved, lgtm, kind/feature

#267 fix: filter nodeconfig event before reconcile
  pkg/clusterlink/agent/controller.go
Labels: size/M, approved, lgtm, kind/bug

#269 fix: fix the leaf node'cidr synced to root cluster
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
Labels: size/XS, approved, lgtm, kind/bug

#272 feat: refactor the leaf resource manager
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/common_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/auto_mcs_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/leaf_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/leaf_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/oneway_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/root_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/leaf_pvc_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/oneway_pvc_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/root_pvc_controller.go
  pkg/clustertree/cluster-manager/node-server/server.go
  pkg/clustertree/cluster-manager/utils/leaf_model_handler.go
  pkg/clustertree/cluster-manager/utils/leaf_resource_manager.go
  pkg/utils/constants.go
  pkg/utils/k8s.go
Labels: approved, lgtm, size/L

#262 feat: Multi-cluster service and log query
  go.mod
  go.sum
  pkg/kosmosctl/get/get.go
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/kosmosctl.go
  pkg/kosmosctl/logs/logs.go
  pkg/kosmosctl/manifest/manifest_clusterrolebindings.go
  pkg/kosmosctl/manifest/manifest_clusterroles.go
  pkg/kosmosctl/manifest/manifest_serviceaccounts.go
  pkg/kosmosctl/uninstall/uninstall.go
  vendor/github.com/fatih/camelcase/.travis.yml
  vendor/github.com/fatih/camelcase/LICENSE.md
  vendor/github.com/fatih/camelcase/README.md
  vendor/github.com/fatih/camelcase/camelcase.go
  vendor/k8s.io/client-go/util/certificate/csr/csr.go
  vendor/k8s.io/kubectl/pkg/apps/kind_visitor.go
  vendor/k8s.io/kubectl/pkg/cmd/apiresources/apiresources.go
  vendor/k8s.io/kubectl/pkg/cmd/apiresources/apiversions.go
  vendor/k8s.io/kubectl/pkg/cmd/logs/logs.go
  vendor/k8s.io/kubectl/pkg/cmd/util/podcmd/podcmd.go
  vendor/k8s.io/kubectl/pkg/describe/describe.go
  vendor/k8s.io/kubectl/pkg/describe/interface.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/attachablepodforobject.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/canbeexposed.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/helpers.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/history.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/historyviewer.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/interface.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/logsforobject.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/mapbasedselectorforobject.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/objectpauser.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/objectrestarter.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/objectresumer.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/portsforobject.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/protocolsforobject.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/rollback.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/rollbacker.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/rollout_status.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/statusviewer.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/updatepodspec.go
  vendor/k8s.io/kubectl/pkg/util/apply.go
  vendor/k8s.io/kubectl/pkg/util/certificate/certificate.go
  vendor/k8s.io/kubectl/pkg/util/completion/completion.go
  vendor/k8s.io/kubectl/pkg/util/deployment/deployment.go
  vendor/k8s.io/kubectl/pkg/util/event/sorted_event_list.go
  vendor/k8s.io/kubectl/pkg/util/fieldpath/fieldpath.go
  vendor/k8s.io/kubectl/pkg/util/pod_port.go
  vendor/k8s.io/kubectl/pkg/util/podutils/podutils.go
  vendor/k8s.io/kubectl/pkg/util/qos/qos.go
  vendor/k8s.io/kubectl/pkg/util/rbac/rbac.go
  vendor/k8s.io/kubectl/pkg/util/resource/resource.go
  vendor/k8s.io/kubectl/pkg/util/service_port.go
  vendor/k8s.io/kubectl/pkg/util/storage/storage.go
  vendor/k8s.io/kubectl/pkg/util/umask.go
  vendor/k8s.io/kubectl/pkg/util/umask_windows.go
  vendor/k8s.io/kubectl/pkg/util/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, kind/feature

#273 fix: incorrect node resources
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/oneway_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/oneway_pvc_controller.go
  pkg/clustertree/cluster-manager/utils/leaf_model_handler.go
  pkg/utils/resources.go
Labels: size/M, approved, lgtm, kind/bug

#274 feat: do not use podIP as the address of the node
  deploy/clustertree-cluster-manager.yml
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
  pkg/clustertree/cluster-manager/utils/leaf_model_handler.go
  pkg/clustertree/cluster-manager/utils/rootcluster.go
Labels: approved, lgtm, size/L

#259 feat: kubectl support install and uninstall node server
  deploy/clustertree-cluster-manager.yml
  hack/cluster.sh
  pkg/cert/cert.go
  pkg/cert/crt.pem
  pkg/cert/key.pem
  pkg/clustertree/cluster-manager/node-server/server.go
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/kosmosctl/manifest/manifest_secrets.go
  pkg/kosmosctl/uninstall/uninstall.go
  pkg/kosmosctl/util/builder.go
Labels: approved, lgtm, size/L, kind/feature

#282 fix: available pod is negative
  pkg/utils/resources.go
Labels: size/S, approved, lgtm

#280 fix: unjoin exception and init leaf model
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/manifest/manifest_crds.go
  pkg/kosmosctl/uninstall/uninstall.go
  pkg/kosmosctl/unjoin/unjoin.go
  pkg/kosmosctl/util/builder.go
  pkg/utils/constants.go
Labels: approved, lgtm, size/L, kind/bug

#283 modify flannel config informer options to avoid the situation when the namespace is custom
  pkg/clusterlink/controllers/cluster/cluster_controller.go
Labels: size/XS, approved, lgtm, kind/bug

#288 fix: cannot create iptable chain in some environment
  deploy/clusterlink-agent.yaml
  pkg/operator/clusterlink/agent/manifests.go
Labels: approved, lgtm

#293 fix: delete pod who is terminating
  pkg/clustertree/cluster-manager/controllers/pod/leaf_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
Labels: size/S, approved, lgtm

#290 feat: add a way to exclude nodes
  deploy/clusterlink-elector.yml
  pkg/clusterlink/controllers/node/node_controller.go
  pkg/operator/clusterlink/elector/manifests.go
  pkg/utils/constants.go
  pkg/utils/k8s.go
Labels: size/M, approved, lgtm, kind/feature

#292 fix: network null pointer exceptions
  pkg/apis/kosmos/v1alpha1/cluster_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/clusterlink/network-manager/handlers/pod_routes.go
  pkg/clusterlink/network-manager/handlers/vxlocal_mac_cache.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/kosmosctl/join/join.go
Labels: size/M, approved, lgtm, kind/bug

#291 add clusterlink code owners
  cmd/clusterlink/OWNERS
Labels: kind/docs, size/S, approved, lgtm

#296 fix: install join nil point
  pkg/kosmosctl/install/install.go
Labels: size/M, approved, lgtm, kind/bug

#289 feat: add rp filter nic
  pkg/clusterlink/network/device.go
Labels: size/S, approved, lgtm, kind/feature

#298 fix clusterlink-controller-manager start err
  pkg/apis/kosmos/v1alpha1/cluster_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: size/S, approved, lgtm, kind/bug

#299 fix: detect NIC by interface name
  cmd/clusterlink/agent/app/agent.go
  cmd/clusterlink/floater/app/floater.go
  pkg/clusterlink/agent-manager/agent_controller.go
  pkg/clusterlink/agent-manager/auto_detect_controller.go
  pkg/clusterlink/agent-manager/autodetection/filtered.go
  pkg/clusterlink/agent-manager/autodetection/interfaces.go
  pkg/clusterlink/agent-manager/network-manager/network_manager.go
Labels: approved, lgtm, size/L, kind/bug

#284 feat: Add e2e-test ci yaml
  .github/workflows/ci.yml
  Makefile
  cluster/images/buildx.kind.Dockerfile
  deploy/clustertree-cluster-manager.yml
  deploy/kosmos-operator.yml
  deploy/kosmos-rbac.yml
  hack/cluster.sh
  hack/local-down-clusterlink.sh
Labels: approved, lgtm, size/L

#303 fix: update clusternode with ip
  pkg/clusterlink/agent-manager/auto_detect_controller.go
Labels: size/XS, approved, lgtm, kind/bug

#301 feat: add the clusters and clusternodes validator
  pkg/clusterlink/network-manager/controller.go
  pkg/clusterlink/network-manager/helpers/filter.go
  pkg/clusterlink/network-manager/network_manager.go
Labels: size/M, approved, lgtm, kind/feature

#305 fix: make p2p available
  pkg/clusterlink/network-manager/helpers/filter.go
Labels: size/XS, approved, lgtm, kind/bug

#300 node_controller do not write ip when interfacename not *
  pkg/clusterlink/controllers/node/node_controller.go
Labels: size/XS, approved, lgtm

#306 fix: add filtering conditions
  cmd/clusterlink/agent/app/agent.go
  pkg/clusterlink/agent-manager/auto_detect_controller.go
  pkg/clusterlink/network/device.go
Labels: size/S, approved, lgtm, kind/bug

#271 feat: Add reserved namespaces to prevent Kosmos from deleting resour…
  cmd/clustertree/cluster-manager/app/manager.go
  cmd/clustertree/cluster-manager/app/options/options.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/auto_mcs_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/serviceexport_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/serviceimport_controller.go
Labels: size/M, approved, lgtm, kind/feature

#215 feature: add PodConversion API
  deploy/crds/kosmos.io_podconversions.yaml
  deploy/crds/kosmos.io_podconvertpolicies.yaml
  pkg/apis/kosmos/v1alpha1/podconvertpolicy_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kosmos/v1alpha1/zz_generated.register.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/fake/fake_kosmos_client.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/fake/fake_podconvertpolicy.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/kosmos_client.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/podconvertpolicy.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/kosmos/v1alpha1/interface.go
  pkg/generated/informers/externalversions/kosmos/v1alpha1/podconvertpolicy.go
  pkg/generated/listers/kosmos/v1alpha1/expansion_generated.go
  pkg/generated/listers/kosmos/v1alpha1/podconvertpolicy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, lgtm, size/XXL, kind/feature

#308 fix: Single cluster network check problem
  pkg/kosmosctl/floater/check.go
  pkg/kosmosctl/floater/floater.go
Labels: size/S, approved, lgtm, kind/bug
