Repository kosmos-io/kosmos, pull requests merged in 2023-08, with the labels that each got.

#1 add code owners
  OWNERS
Labels: size/S

#3 modify workflows--modify static list
  .github/workflows/migrate_github_repos_to_gitee.yaml
Labels: size/XS, approved, lgtm

#2 modify kosmos readme md
  README.md
  README_zh.md
Labels: size/M, approved, lgtm

#5 fix: Added single-cluster network protection
  pkg/constants/network.go
  pkg/network-manager/handlers/host_network.go
  pkg/network-manager/handlers/pod_routes.go
  pkg/network-manager/handlers/vxbridge_mac_cache.go
  pkg/network-manager/handlers/vxbridge_network.go
  pkg/network-manager/handlers/vxlocal_mac_cache.go
  pkg/network-manager/handlers/vxlocal_network.go
  pkg/network-manager/helpers/network.go
  pkg/network-manager/helpers/network_test.go
Labels: bug, approved, lgtm, size/L

#6 create ippool use GlobalCIDRsMap
  pkg/controllers/calicoippool/calicoippool_controller.go
Labels: invalid, size/S, approved, lgtm

#7 feat: print log during create vxlan device
  Makefile
  cmd/agent/app/agent.go
  pkg/agent/controller.go
  pkg/agent/network-manager/network_manager.go
  pkg/network/adapter.go
  pkg/network/constant.go
  pkg/network/device.go
  pkg/network/interface.go
Labels: approved, lgtm, size/L

#8 modify kosmos readme
  README.md
  README_zh.md
Labels: size/XS, approved, lgtm

#9 feat: intercommunication between subclusters
  pkg/constants/network.go
  pkg/network-manager/handlers/globalmap.go
  pkg/network-manager/network_manager.go
Labels: size/M, approved, lgtm

#10 change group name to kosmos
  README_zh.md
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllerstarter.go
  deploy/crds/kosmos.io_clusternodes.yaml
  deploy/crds/kosmos.io_clusters.yaml
  deploy/crds/kosmos.io_nodeconfigs.yaml
  examples/cluster-demo.yaml
  generate/generate.go
  hack/cluster.sh
  pkg/apis/clusterlink/v1alpha1/doc.go
  pkg/apis/clusterlink/v1alpha1/zz_generated.register.go
  pkg/clusterlinkctl/floaterclient/cluster-helper.go
  pkg/clusterlinkctl/floaterclient/manifests_floater.go
  pkg/clusterlinkctl/initmaster/ctlmaster/deploy_crd.go
  pkg/clusterlinkctl/initmaster/ctlmaster/manifests_crd.go
  pkg/clusterlinkctl/membercurd/options.go
  pkg/controllers/calicoippool/calicoippool_controller.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/node/node_controller.go
  pkg/controllers/nodecidr/nodecidr_controller.go
  pkg/elector/elector.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/clusterlink/v1alpha1/cluster.go
  pkg/generated/clientset/versioned/typed/clusterlink/v1alpha1/clusterlink_client.go
  pkg/generated/clientset/versioned/typed/clusterlink/v1alpha1/clusternode.go
  pkg/generated/clientset/versioned/typed/clusterlink/v1alpha1/fake/fake_cluster.go
  pkg/generated/clientset/versioned/typed/clusterlink/v1alpha1/fake/fake_clusterlink_client.go
  pkg/generated/clientset/versioned/typed/clusterlink/v1alpha1/fake/fake_clusternode.go
  pkg/generated/clientset/versioned/typed/clusterlink/v1alpha1/fake/fake_nodeconfig.go
  pkg/generated/clientset/versioned/typed/clusterlink/v1alpha1/nodeconfig.go
  pkg/generated/informers/externalversions/clusterlink/v1alpha1/cluster.go
  pkg/generated/informers/externalversions/clusterlink/v1alpha1/clusternode.go
  pkg/generated/informers/externalversions/clusterlink/v1alpha1/nodeconfig.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/linkctl/get/get.go
  pkg/operator/addons/agent/manifests.go
  pkg/operator/addons/elector/manifests.go
  pkg/operator/addons/manager/manifests.go
  pkg/operator/addons/proxy/manifests.go
  pkg/operator/addons/proxy/proxy.go
  pkg/proxy/store/cluster_cache.go
  test/e2e/elector_test.go
  test/e2e/framework/cluster.go
Labels: approved, lgtm, size/L
