Repository kosmos-io/kosmos, pull requests merged in 2024-05, with the labels that each got.

#505 fix: restore the way of getting ip and port for api server
  pkg/kubenest/tasks/upload.go
Labels: approved, lgtm, kind/bug

#503 fix virtualcluster deploy yaml and virtualcluster controller bug
  cmd/kubenest/operator/app/operator.go
  deploy/virtual-cluster-operator.yml
  pkg/kubenest/constants/constant.go
  pkg/kubenest/controller/virtualcluster_init_controller.go
  pkg/kubenest/tasks/manifests_components.go
Labels: approved, lgtm, do-not-merge/hold, kind/bug

#506 modify some codes for coredns and mainfest_components
  pkg/kubenest/constants/constant.go
  pkg/kubenest/init.go
  pkg/kubenest/tasks/coredns.go
  pkg/kubenest/tasks/manifests_components.go
  pkg/kubenest/util/helper.go
Labels: approved, lgtm, kind/bug

#507 add uninstall coredns feature and fix globalnode status bug
  pkg/apis/kosmos/v1alpha1/global_node_types.go
  pkg/kubenest/controller/virtualcluster.node.controller/node_controller.go
  pkg/kubenest/controller/virtualcluster_init_controller.go
  pkg/kubenest/init.go
  pkg/kubenest/tasks/coredns.go
Labels: approved, lgtm, kind/bug

#504 fix: node-agent exit with 2, when file not found and remove useless s…
  cmd/kubenest/node-agent/app.go
  hack/node-agent/build.sh
  hack/node-agent/clean.sh
  hack/node-agent/count.sh
  hack/node-agent/install.sh
  hack/node-agent/node-agent.service
Labels: approved, lgtm

#508 refactor: delete coredns by yaml
  cluster/images/agent.Dockerfile
  cluster/images/buildx.agent.Dockerfile
  pkg/kubenest/tasks/coredns.go
  pkg/kubenest/util/helper.go
Labels: approved, lgtm, kind/feature

#511 reactor code and fix some bug
  pkg/kubenest/constants/constant.go
  pkg/kubenest/controlplane/component.go
  pkg/kubenest/controlplane/rbac.go
  pkg/kubenest/manifest/controlplane/kubecontroller/manifests_deployment.go
  pkg/kubenest/manifest/controlplane/scheduler/manifest_configmap.go
  pkg/kubenest/manifest/controlplane/scheduler/manifest_deployment.go
  pkg/kubenest/manifest/controlplane/scheduler/manifests_rbac.go
Labels: approved, lgtm, kind/cleanup

#516 feat: sync label from globalnode to node
  cmd/kubenest/operator/app/operator.go
  pkg/kubenest/constants/constant.go
  pkg/kubenest/controller/global.node.controller/global_node_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/node_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/task.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/workflow.go
  pkg/kubenest/util/util.go
Labels: approved, lgtm, kind/feature

#517 feat: add shortname for virtualcluster
  deploy/crds/kosmos.io_globalnodes.yaml
  deploy/crds/kosmos.io_virtualclusters.yaml
  pkg/apis/kosmos/v1alpha1/virtualcluster_types.go
Labels: approved, lgtm, kind/feature

#510 fix: skip spec.nodeName env populated for downwardAPI
  pkg/utils/lifted/env.go
Labels: approved, lgtm, kind/bug

#527 fix: node-agent restart when the version not changed #526
  deploy/virtual-cluster-operator.yml
  hack/node-agent/init.sh
  hack/node-agent/start.sh
Labels: approved, lgtm

#514 fix: modify some codes about the bug of namespace is int
  examples/vitual-cluster-demo.yaml
  pkg/kubenest/controlplane/apiserver.go
  pkg/kubenest/controlplane/component.go
  pkg/kubenest/controlplane/etcd.go
  pkg/kubenest/controlplane/rbac.go
  pkg/kubenest/controlplane/service.go
  pkg/kubenest/tasks/coredns.go
  pkg/kubenest/tasks/manifests_components.go
  pkg/kubenest/util/cert/certs.go
  pkg/kubenest/util/template.go
Labels: approved, lgtm, kind/bug

#534 feat: create convert-related crds when join cluster
  deploy/crds/kosmos.io_clusterpodconvertpolicies.yaml
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/manifest/manifest_crds.go
Labels: approved, lgtm, kind/feature

#528 fix: Modify the ip in the kubeconfig used by the host cluster to cluster ip
  deploy/crds/kosmos.io_clusterpodconvertpolicies.yaml
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/manifest/manifest_crds.go
  pkg/kubenest/controlplane/apiserver.go
  pkg/kubenest/controlplane/component.go
  pkg/kubenest/controlplane/service.go
  pkg/kubenest/tasks/upload.go
Labels: approved, lgtm, kind/feature

#536 Revert "fix: Modify the ip in the kubeconfig used by the host cluster to cluster ip"
  deploy/crds/kosmos.io_clusterpodconvertpolicies.yaml
  pkg/kosmosctl/join/join.go
  pkg/kosmosctl/manifest/manifest_crds.go
  pkg/kubenest/controlplane/apiserver.go
  pkg/kubenest/controlplane/component.go
  pkg/kubenest/controlplane/service.go
  pkg/kubenest/tasks/upload.go
Labels: approved

#537 feat: add admin-config-clusterip secret use cluster ip and port
  pkg/kubenest/controlplane/apiserver.go
  pkg/kubenest/controlplane/component.go
  pkg/kubenest/controlplane/service.go
  pkg/kubenest/tasks/upload.go
Labels: kind/feature

#533 feat: add taint for node
  deploy/virtual-cluster-operator.yml
  hack/kubelet_node_helper.sh
  hack/node_agent_backup.sh
  pkg/kubenest/controller/global.node.controller/global_node_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/env/env.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/task.go
Labels: approved, lgtm, kind/feature

#552 add skip to skip some task
  cmd/clustertree/cluster-manager/app/options/options.go
  cmd/kubenest/operator/app/operator.go
  cmd/kubenest/operator/app/options/options.go
  pkg/kubenest/controller/virtualcluster.node.controller/node_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/task.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/workflow.go
Labels: approved, lgtm, kind/feature

#547 pod convert policy code cleanup in main
  deploy/crds/kosmos.io_clusterpodconvertpolicies.yaml
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/join/join.go
  pkg/kubenest/controller/kosmos/kosmos_join_controller.go
  pkg/utils/podutils/pod_convert.go
Labels: lgtm

#535 add api for virtualcluster plugin
  deploy/crds/kosmos.io_clusterpodconvertpolicies.yaml
  deploy/crds/kosmos.io_virtualclusterplugins.yaml
  deploy/crds/kosmos.io_virtualclusters.yaml
  pkg/apis/kosmos/v1alpha1/virtualcluster_types.go
  pkg/apis/kosmos/v1alpha1/virtualclusterplugin_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kosmos/v1alpha1/zz_generated.register.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/fake/fake_kosmos_client.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/fake/fake_virtualclusterplugin.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/kosmos_client.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/virtualclusterplugin.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/kosmos/v1alpha1/interface.go
  pkg/generated/informers/externalversions/kosmos/v1alpha1/virtualclusterplugin.go
  pkg/generated/listers/kosmos/v1alpha1/expansion_generated.go
  pkg/generated/listers/kosmos/v1alpha1/virtualclusterplugin.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, kind/feature

#574 fix: DNS configuration exception
  deploy/virtual-cluster-host-port-cm.yaml
  deploy/virtual-cluster-operator.yml
  hack/k8s-in-k8s/env.dev.sh
  hack/k8s-in-k8s/env.sh
  hack/k8s-in-k8s/generate_env.sh
  hack/k8s-in-k8s/kubelet_node_helper.sh
  pkg/kubenest/controller/global.node.controller/global_node_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/env/env.go
  pkg/kubenest/controller/virtualcluster.node.controller/node_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/task.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/workflow.go
Labels: approved, lgtm

#613 Cherry-Pick: fix anpDeployment template error and update apiserver replicas to 2
  cmd/kubenest/operator/app/options/options.go
  pkg/kubenest/constants/constant.go
  pkg/kubenest/controlplane/apiserver.go
  pkg/kubenest/tasks/anp.go
Labels: approved, lgtm
