Repository kosmos-io/kosmos, pull requests merged in 2024-03, with the labels that each got.

#426 fix: kosmos scheduler e2e cases
  docs/proposals/distributionpolicy/README.md
  pkg/scheduler/lifted/plugins/leafnodetainttoleration/leafnode_tainttoleration.go
  test/e2e/framework/distribution_policy_sample.go
Labels: size/S, approved, lgtm, kind/failing-test

#417 feature: precheck ns and api-resources in sync leaf
  cmd/clustertree/cluster-manager/app/manager.go
  cmd/clustertree/cluster-manager/app/options/options.go
  examples/promote_policy_demo.yaml
  pkg/clustertree/cluster-manager/controllers/promote/precheck/precheck.go
  pkg/clustertree/cluster-manager/controllers/promote/promote_policy_controller.go
  pkg/clustertree/cluster-manager/controllers/promote/requests/request.go
  pkg/clustertree/cluster-manager/controllers/promote/utils/utils.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/utils/constants.go
Labels: approved, lgtm, size/L, kind/feature

#425 update github ci workflow fix e2e run failed
  .github/workflows/ci.yml
  hack/cluster.sh
  hack/clustertemplete/kindconfig
  hack/rune2e.sh
  hack/verify-staticcheck.sh
Labels: approved, lgtm, size/L, kind/failing-test

#427 fix: kosmos node address throw duplicate value error
  pkg/clustertree/cluster-manager/utils/leaf_model_handler.go
Labels: size/S, approved, lgtm, kind/bug

#429 cherry-pick: kosmos node address throw duplicate value error
  pkg/clustertree/cluster-manager/utils/leaf_model_handler.go
Labels: size/S, approved, lgtm, kind/bug

#428 cherry-pick: kosmos node address throw duplicate value error
  pkg/clustertree/cluster-manager/utils/leaf_model_handler.go
Labels: size/S, approved, lgtm, kind/bug

#430 feature: add rollback for promote feature
  cmd/clustertree/cluster-manager/app/manager.go
  deploy/crds/kosmos.io_promotepolicies.yaml
  pkg/apis/kosmos/v1alpha1/promotepolicy_types.go
  pkg/clustertree/cluster-manager/controllers/pod/leaf_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/promote/backup/item_backupper.go
  pkg/clustertree/cluster-manager/controllers/promote/backup/register_action.go
  pkg/clustertree/cluster-manager/controllers/promote/detach/detach.go
  pkg/clustertree/cluster-manager/controllers/promote/detach/pod_detach_action.go
  pkg/clustertree/cluster-manager/controllers/promote/detach/pvc_detach_action.go
  pkg/clustertree/cluster-manager/controllers/promote/detach/register_action.go
  pkg/clustertree/cluster-manager/controllers/promote/detach/sts_deploy_detach_action.go
  pkg/clustertree/cluster-manager/controllers/promote/detach/universal_detach_action.go
  pkg/clustertree/cluster-manager/controllers/promote/discovery/helper.go
  pkg/clustertree/cluster-manager/controllers/promote/kuberesource/kuberesource.go
  pkg/clustertree/cluster-manager/controllers/promote/promote_policy_controller.go
  pkg/clustertree/cluster-manager/controllers/promote/requests/request.go
  pkg/clustertree/cluster-manager/controllers/promote/restore/pod_restore_action.go
  pkg/clustertree/cluster-manager/controllers/promote/restore/pv_restore_action.go
  pkg/clustertree/cluster-manager/controllers/promote/restore/register_action.go
  pkg/clustertree/cluster-manager/controllers/promote/restore/restore.go
  pkg/clustertree/cluster-manager/controllers/promote/restore/service_restore_action.go
  pkg/clustertree/cluster-manager/controllers/promote/restore/sts_deploy_restore_action.go
  pkg/clustertree/cluster-manager/controllers/promote/restore/universal_restore_action.go
  pkg/clustertree/cluster-manager/controllers/promote/types/types.go
  pkg/clustertree/cluster-manager/controllers/promote/utils/kube/kube_utils.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, lgtm, size/XXL, kind/feature

#424 title: virtualcluster join controller
  cmd/clustertree-operator/app/tree_operator.go
  deploy/crds/kosmos.io_virtualclusters.yaml
  pkg/kosmosctl/manifest/manifest_crds.go
  pkg/treeoperator/constants/constant.go
  pkg/treeoperator/controller/virtualcluster_join_controller.go
  pkg/treeoperator/manifest/manifest_deployments.go
  pkg/treeoperator/manifest/manifest_secrets.go
Labels: approved, lgtm, size/XL, kind/feature

#431 e2e:update e2e test script and quick start script
  .github/workflows/ci.yml
  examples/nginx-demo.yaml
  hack/cluster.sh
  hack/clustertemplete/kindconfig
  hack/local-cleanup-kosmos.sh
  hack/local-down-clusterlink.sh
  hack/local-up-clusterlink.sh
  hack/local-up-kosmos.sh
  hack/prepare-e2e.sh
  hack/rune2e.sh
  hack/util.sh
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/join/join.go
  test/e2e/deploy/mysql-operator/mysqll-operator.yaml
  test/e2e/deploy/nginx/nginx.yaml
Labels: approved, lgtm, size/XL, kind/failing-test

#437 e2e: use latest tag for e2e test and delete 0.2.0 tag
  hack/cluster.sh
  hack/rune2e.sh
Labels: approved, lgtm

#434 title: fix bug,some times clusternode created without podcidr
  pkg/clusterlink/controllers/nodecidr/adapter.go
  pkg/clusterlink/controllers/nodecidr/nodecidr_controller.go
Labels: size/M, approved, lgtm, kind/bug

#444 fix: Elegant deletion of pods in sub-clusters (consistent with k8s)
  pkg/clustertree/cluster-manager/controllers/pod/leaf_pod_controller.go
Labels: approved, lgtm

#443 fix: Elegant deletion of pods in sub-clusters (consistent with k8s)
  pkg/clustertree/cluster-manager/controllers/pod/leaf_pod_controller.go
Labels: approved, lgtm

#449 fix: fix update SA ObjectReference Concurrent
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
Labels: approved, lgtm

#446 cherry-pick: fix bug,some times clusternode created without podcidr
  pkg/clusterlink/controllers/nodecidr/adapter.go
  pkg/clusterlink/controllers/nodecidr/nodecidr_controller.go
Labels: approved, lgtm

#452 fix: status synchronization error of virtual node in one2one model mode
  pkg/clustertree/cluster-manager/utils/leaf_model_handler.go
Labels: approved, lgtm

#454 fix: pod convert nil value exception
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
Labels: approved, lgtm

#455 fix: fix the informer panic issue
  pkg/clustertree/cluster-manager/controllers/mcs/serviceimport_controller.go
Labels: approved, lgtm

#451 fix: LeafMode-Node supports taints migration
  pkg/clustertree/cluster-manager/utils/leaf_model_handler.go
Labels: approved, lgtm
