Repository kosmos-io/kosmos, pull requests merged in 2024-06, with the labels that each got.

#612 fix: fix anpDeployment template error and update apiserver replicas to 2
  cmd/kubenest/operator/app/options/options.go
  pkg/kubenest/constants/constant.go
  pkg/kubenest/controlplane/apiserver.go
  pkg/kubenest/tasks/anp.go
Labels: approved, lgtm

#614 fix: node label lost
  cmd/kubenest/operator/app/options/options.go
  pkg/kubenest/controller/global.node.controller/global_node_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/env/env.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/task.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/workflow.go
  pkg/kubenest/tasks/coredns.go
  pkg/kubenest/tasks/manifests_components.go
Labels: approved, lgtm

#615 Cherry Pick: node label lost
  cmd/kubenest/operator/app/options/options.go
  pkg/kubenest/controller/global.node.controller/global_node_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/env/env.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/task.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/workflow.go
  pkg/kubenest/tasks/manifests_components.go
Labels: approved, lgtm, kind/bug

#616 Cherry-Picked: update apiserver anp deploy spec.strategy to Recreate
  pkg/kubenest/manifest/controlplane/apiserver/mainfests_deployment.go
Labels: approved, lgtm

#617 fix: update apiserver anp deploy spec.strategy to Recreate
  pkg/kubenest/manifest/controlplane/apiserver/mainfests_deployment.go
Labels: approved, lgtm

#619 Cherry-Pick: add check apiserver before create agent deploy
  pkg/kubenest/tasks/anp.go
Labels: approved, lgtm

#618 fix: add check apiserver before create agent deploy
  pkg/kubenest/tasks/anp.go
Labels: approved, lgtm

#623 fix: concurrent execution of change node tasks
  cmd/kubenest/operator/app/operator.go
  hack/k8s-in-k8s/free_globalnodes.sh
  hack/k8s-in-k8s/globalnodes_helper.sh
  pkg/kubenest/controller/virtualcluster.node.controller/env/env.go
  pkg/kubenest/controller/virtualcluster.node.controller/node_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/logger.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/task.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/workflow.go
  pkg/kubenest/tasks/anp.go
Labels: approved, lgtm

#624 Cherry Pick: concurrent execution of change node tasks
  cmd/kubenest/operator/app/operator.go
  hack/k8s-in-k8s/free_globalnodes.sh
  hack/k8s-in-k8s/globalnodes_helper.sh
  pkg/kubenest/controller/virtualcluster.node.controller/env/env.go
  pkg/kubenest/controller/virtualcluster.node.controller/node_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/logger.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/task.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/workflow.go
  pkg/kubenest/tasks/anp.go
Labels: approved, lgtm, kind/feature

#625 feat: support plugin options for templete
  deploy/crds/kosmos.io_virtualclusters.yaml
  examples/vitual-cluster-demo.yaml
  pkg/apis/kosmos/v1alpha1/virtualcluster_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/kubenest/init.go
  pkg/kubenest/tasks/coredns.go
  pkg/kubenest/tasks/data.go
  pkg/kubenest/tasks/manifests_components.go
  pkg/kubenest/util/template.go
Labels: approved, lgtm, kind/feature

#627 Cherry Pick: support plugin options for templete
  deploy/crds/kosmos.io_virtualclusters.yaml
  examples/vitual-cluster-demo.yaml
  pkg/apis/kosmos/v1alpha1/virtualcluster_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/kubenest/init.go
  pkg/kubenest/tasks/coredns.go
  pkg/kubenest/tasks/data.go
  pkg/kubenest/tasks/manifests_components.go
  pkg/kubenest/util/template.go
Labels: approved, lgtm, kind/feature

#626 fix: Fixed core-dns yaml format issues
  pkg/kubenest/manifest/controlplane/coredns/host/manifest_deployment.go
  pkg/kubenest/util/helper.go
Labels: approved, lgtm, kind/bug

#594 fix: add kube-proxy in virtualcluster
  cmd/kubenest/operator/app/options/options.go
  pkg/kubenest/constants/constant.go
  pkg/kubenest/controlplane/component.go
  pkg/kubenest/controlplane/proxy.go
  pkg/kubenest/init.go
  pkg/kubenest/manifest/controlplane/kubecontroller/manifests_deployment.go
  pkg/kubenest/manifest/controlplane/proxy/mainfests_daemonset.go
  pkg/kubenest/manifest/controlplane/proxy/manifests_rbac.go
  pkg/kubenest/tasks/component.go
  pkg/kubenest/tasks/proxy.go
  pkg/kubenest/util/helper.go
Labels: approved, lgtm

#628 feat: install api-server-external-service in virtualcluster
  cmd/kubenest/operator/app/operator.go
  pkg/kubenest/constants/constant.go
  pkg/kubenest/controller/endpoints.sync.controller/apiserver_external_sync_controller.go
  pkg/kubenest/controlplane/endpoint.go
  pkg/kubenest/init.go
  pkg/kubenest/manifest/controlplane/virtualcluster/manifests_service.go
  pkg/kubenest/tasks/coredns.go
  pkg/kubenest/tasks/endpoint.go
Labels: approved, lgtm, kind/feature

#632 fix: Fix exceptions that occur when adding nodes back to the host clu…
  hack/k8s-in-k8s/generate_env.sh
  hack/k8s-in-k8s/kubelet_node_helper.sh
  hack/k8s-in-k8s/port_check.sh
Labels: approved, lgtm, kind/bug

#633 Cherry Pick: Fix exceptions that occur when adding nodes back to the host clu…
  hack/k8s-in-k8s/generate_env.sh
  hack/k8s-in-k8s/kubelet_node_helper.sh
  hack/k8s-in-k8s/port_check.sh
Labels: approved, lgtm, kind/bug

#637 feat: support ipv6
  pkg/kubenest/constants/constant.go
  pkg/kubenest/controller/virtualcluster.node.controller/env/env.go
  pkg/kubenest/controller/virtualcluster.node.controller/exector/exector.go
  pkg/kubenest/controller/virtualcluster.node.controller/exector/remote_cmd.go
  pkg/kubenest/controlplane/apiserver.go
  pkg/kubenest/controlplane/component.go
  pkg/kubenest/controlplane/etcd.go
  pkg/kubenest/manifest/controlplane/apiserver/mainfests_deployment.go
  pkg/kubenest/manifest/controlplane/etcd/mainfests_deployment.go
  pkg/kubenest/manifest/controlplane/kubecontroller/manifests_deployment.go
  pkg/kubenest/manifest/controlplane/scheduler/manifest_deployment.go
  pkg/kubenest/tasks/anp.go
  pkg/kubenest/tasks/upload.go
  pkg/kubenest/util/cert/certs.go
  pkg/kubenest/util/image.go
  pkg/kubenest/util/util.go
  pkg/utils/utils.go
Labels: approved, lgtm, kind/feature

#630 support labelselector and add retry mechanism when update globalnode
  pkg/kubenest/constants/constant.go
  pkg/kubenest/controller/virtualcluster.node.controller/selector/labelselector.go
  pkg/kubenest/controller/virtualcluster_init_controller.go
  pkg/kubenest/util/util.go
Labels: approved, lgtm, kind/feature

#639 Make etcd's stored data more flexible and configurable
  cmd/kubenest/operator/app/options/options.go
  deploy/crds/kosmos.io_virtualclusters.yaml
  deploy/virtual-cluster-host-port-cm.yaml
  deploy/virtual-cluster-operator.yml
  hack/cluster.sh
  pkg/apis/kosmos/v1alpha1/virtualcluster_types.go
  pkg/kubenest/controller/virtualcluster.node.controller/selector/labelselector.go
  pkg/kubenest/controller/virtualcluster_init_controller.go
  pkg/kubenest/controlplane/etcd.go
  pkg/kubenest/init.go
  pkg/kubenest/manifest/controlplane/etcd/mainfests_deployment.go
  pkg/kubenest/tasks/data.go
  pkg/kubenest/tasks/etcd.go
Labels: approved, lgtm, kind/feature

#640 cherry-pick: install api-server-external-service in virtualcluster
  cmd/kubenest/operator/app/operator.go
  pkg/kubenest/constants/constant.go
  pkg/kubenest/controller/endpoints.sync.controller/apiserver_external_sync_controller.go
  pkg/kubenest/controlplane/endpoint.go
  pkg/kubenest/init.go
  pkg/kubenest/manifest/controlplane/virtualcluster/manifests_service.go
  pkg/kubenest/tasks/coredns.go
  pkg/kubenest/tasks/endpoint.go
Labels: kind/feature

#638 feat: support ipv6
  pkg/kubenest/constants/constant.go
  pkg/kubenest/controller/virtualcluster.node.controller/env/env.go
  pkg/kubenest/controller/virtualcluster.node.controller/exector/exector.go
  pkg/kubenest/controller/virtualcluster.node.controller/exector/remote_cmd.go
  pkg/kubenest/controlplane/apiserver.go
  pkg/kubenest/controlplane/component.go
  pkg/kubenest/controlplane/etcd.go
  pkg/kubenest/manifest/controlplane/apiserver/mainfests_deployment.go
  pkg/kubenest/manifest/controlplane/etcd/mainfests_deployment.go
  pkg/kubenest/manifest/controlplane/kubecontroller/manifests_deployment.go
  pkg/kubenest/manifest/controlplane/scheduler/manifest_deployment.go
  pkg/kubenest/tasks/anp.go
  pkg/kubenest/tasks/upload.go
  pkg/kubenest/util/cert/certs.go
  pkg/kubenest/util/image.go
  pkg/kubenest/util/util.go
  pkg/utils/utils.go
Labels: approved, kind/feature
