Repository kosmos-io/kosmos, pull requests merged in 2024-02, with the labels that each got.

#400 cherry-pick: don't update address of node in node-resources-controller
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
Labels: size/XS, approved, lgtm

#399 fix: don't update address of node in node-resources-controller
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
Labels: size/XS, approved, lgtm, kind/bug

#396 optimize some func name
  cmd/clusterlink/network-manager/app/manager.go
  cmd/clusterlink/network-manager/main.go
  cmd/clustertree/cluster-manager/app/manager.go
  cmd/clustertree/cluster-manager/main.go
Labels: size/XS, approved, lgtm, kind/cleanup

#395 delete unsed files
  .github/workflows/e2e.yml
Labels: size/S, approved, lgtm, kind/cleanup

#401 cherry-pick: don't update address of node in node-resources-controller
  pkg/clustertree/cluster-manager/controllers/node_resources_controller.go
Labels: size/XS, approved, lgtm, kind/bug

#405 fix:validate args with kosmos join, create ServiceExport/ServiceImport crd with kosmos install
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/join/join.go
Labels: approved, lgtm, size/L, kind/bug

#406 change the name of kosmos-operator to clusterlink-operator
  Makefile
  cmd/clusterlink/clusterlink-operator/app/operator.go
  cmd/clusterlink/clusterlink-operator/app/options/options.go
  cmd/clusterlink/clusterlink-operator/app/options/validation.go
  cmd/clusterlink/clusterlink-operator/main.go
  cmd/koslet/OWNERS
  cmd/koslet/app/server.go
  cmd/koslet/main.go
  deploy/kosmos-operator.yml
  deploy/kosmos-rbac.yml
  docs/proposals/kosmosctl/offline_installation_zh.md
  hack/cluster.sh
  hack/util.sh
  pkg/clusterlink/clusterlink-operator/agent/agent.go
  pkg/clusterlink/clusterlink-operator/agent/manifests.go
  pkg/clusterlink/clusterlink-operator/elector/elector.go
  pkg/clusterlink/clusterlink-operator/elector/manifests.go
  pkg/clusterlink/clusterlink-operator/global/global.go
  pkg/clusterlink/clusterlink-operator/global/manifests.go
  pkg/clusterlink/clusterlink-operator/install.go
  pkg/clusterlink/clusterlink-operator/manager/manager.go
  pkg/clusterlink/clusterlink-operator/manager/manifests.go
  pkg/clusterlink/clusterlink-operator/operator_controller.go
  pkg/clusterlink/clusterlink-operator/option/option.go
  pkg/clusterlink/clusterlink-operator/proxy/manifests.go
  pkg/clusterlink/clusterlink-operator/proxy/proxy.go
  pkg/clusterlink/clusterlink-operator/utils/idempotency.go
  pkg/clusterlink/clusterlink-operator/utils/template.go
  pkg/kosmosctl/install/install.go
  pkg/kosmosctl/manifest/manifest_clusterrolebindings.go
  pkg/kosmosctl/manifest/manifest_deployments.go
  pkg/kosmosctl/manifest/manifest_serviceaccounts.go
  pkg/kosmosctl/uninstall/uninstall.go
  pkg/utils/constants.go
Labels: approved, lgtm, size/L, kind/cleanup

#410 add propasal tempalte
  docs/proposals/template/propasal_template.md
Labels: size/M, approved, lgtm, kind/feature

#411 Proposal: add proposal for implement k8s in k8s by kosmos
  docs/proposals/k8sink8s/img/Kubernetes_in_Kubernetes.svg
  docs/proposals/k8sink8s/kubernetes_inkubernetes.md
Labels: size/M, approved, lgtm, kind/feature

#412 Add VirtualCluster api
  deploy/crds/kosmos.io_virtualclusters.yaml
  pkg/apis/kosmos/v1alpha1/virtualcluster_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kosmos/v1alpha1/zz_generated.register.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/fake/fake_kosmos_client.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/fake/fake_virtualcluster.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/kosmos_client.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/virtualcluster.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/kosmos/v1alpha1/interface.go
  pkg/generated/informers/externalversions/kosmos/v1alpha1/virtualcluster.go
  pkg/generated/listers/kosmos/v1alpha1/expansion_generated.go
  pkg/generated/listers/kosmos/v1alpha1/virtualcluster.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, lgtm, size/XL

#413 init VirtualCluster impl framework
  cmd/clustertree-operator/OWNERS
  cmd/clustertree-operator/app/options/options.go
  cmd/clustertree-operator/app/options/validation.go
  cmd/clustertree-operator/app/tree_operator.go
  cmd/clustertree-operator/main.go
  pkg/treeoperator/virtualcluster_init_controller.go
  pkg/treeoperator/virtualcluster_join_controller.go
Labels: approved, lgtm, size/L, kind/feature

#415 fix: status synchronization error of virtual node in one2one model mode
  pkg/clustertree/cluster-manager/utils/leaf_model_handler.go
Labels: size/XS, approved, lgtm, kind/bug

#403 fix: update projected in feature_sync_leaf
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/utils/constants.go
Labels: approved, lgtm, size/L, kind/bug

#321 feature: add distribution policy for release-1.26.3
  deploy/crds/kosmos.io_clusterdistributionpolicies.yaml
  deploy/crds/kosmos.io_distributionpolicies.yaml
  docs/proposals/distributionpolicy/README.md
  pkg/apis/kosmos/v1alpha1/distributionpolicy_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kosmos/v1alpha1/zz_generated.register.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/clusterdistributionpolicy.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/distributionpolicy.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/fake/fake_clusterdistributionpolicy.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/fake/fake_distributionpolicy.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/fake/fake_kosmos_client.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/kosmos_client.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/kosmos/v1alpha1/clusterdistributionpolicy.go
  pkg/generated/informers/externalversions/kosmos/v1alpha1/distributionpolicy.go
  pkg/generated/informers/externalversions/kosmos/v1alpha1/interface.go
  pkg/generated/listers/kosmos/v1alpha1/clusterdistributionpolicy.go
  pkg/generated/listers/kosmos/v1alpha1/distributionpolicy.go
  pkg/generated/listers/kosmos/v1alpha1/expansion_generated.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, lgtm, size/XXL, kind/feature

#422 Initialize part of the process of creating a virtual control plane
  cmd/clustertree-operator/app/options/options.go
  cmd/clustertree-operator/app/tree_operator.go
  deploy/crds/kosmos.io_virtualclusters.yaml
  examples/vitual-cluster-demo.yaml
  pkg/apis/kosmos/v1alpha1/virtualcluster_types.go
  pkg/treeoperator/constants/constant.go
  pkg/treeoperator/controller/virtualcluster_init_controller.go
  pkg/treeoperator/controller/virtualcluster_join_controller.go
  pkg/treeoperator/virtualcluster_init_controller.go
  pkg/treeoperator/workflow/execute.go
  pkg/treeoperator/workflow/phase.go
Labels: approved, lgtm, size/L, kind/feature

#419 feature: add e2e and distribution policy
  cmd/scheduler/main.go
  deploy/scheduler/deployment.yaml
  deploy/scheduler/rbac.yaml
  hack/cluster.sh
  pkg/scheduler/lifted/plugins/leafnodedistribution/leafnode_distribution_policy.go
  test/e2e/framework/deployment_sample.go
  test/e2e/framework/distribution_policy_sample.go
  test/e2e/framework/namespace_sample.go
  test/e2e/framework/pod_sample.go
  test/e2e/leaf_node_test.go
  test/e2e/scheduler_distribution_policy_test.go
Labels: approved, lgtm, size/XL, kind/feature
