Repository kosmos-io/kosmos, pull requests merged in 2024-01, with the labels that each got.

#329 feature: support pod convert
  deploy/crds/kosmos.io_podconvertpolicies.yaml
  pkg/apis/kosmos/v1alpha1/podconvertpolicy_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/utils/constants.go
  pkg/utils/convertpolicy/pod.go
  pkg/utils/podutils/pod_convert.go
Labels: size/L, kind/feature

#350 fix: add cluster-member3 for leafnode mode e2e test
  hack/cluster.sh
  hack/prepare-e2e.sh
  hack/rune2e.sh
  test/e2e/framework/deployment_sample.go
  test/e2e/leaf_node_test.go
  test/e2e/suit_test.go
Labels: size/M, approved, lgtm

#361 fix: synch code to new gitee repository
  .github/workflows/sync_to_gitee.yaml
Labels: size/XS, approved, lgtm, kind/bug

#353 fix: exclude non-Running pods when calculating node resources
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/utils/resources.go
Labels: approved, lgtm

#369 add docs for offline_installation
  docs/proposals/kosmosctl/img/kosmos-installation.png
  docs/proposals/kosmosctl/offline_installation_zh.md
  pkg/kosmosctl/image/pull.go
  pkg/utils/constants.go
Labels: approved, lgtm, size/L

#340 feature: adapt projected volume in any version
  pkg/clustertree/cluster-manager/controllers/common_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/storage_handler.go
  pkg/utils/constants.go
  pkg/utils/k8s.go
  pkg/utils/podutils/pod.go
Labels: approved, lgtm, size/L

#371 title: fix cni compatibility issue, cluster with calico can't create …
  pkg/clusterlink/controllers/calicoippool/calicoippool_controller.go
Labels: size/XS, approved, lgtm, kind/bug

#379 fix: fix the informer panic issue
  pkg/clustertree/cluster-manager/controllers/mcs/serviceimport_controller.go
Labels: size/S, approved, lgtm, kind/bug

#380 fix: fix the informer panic issue
  pkg/clustertree/cluster-manager/controllers/mcs/serviceimport_controller.go
Labels: size/S, approved, lgtm

#382 feat: enhance permissions for OrangeBao
  OWNERS
Labels: size/XS, approved, lgtm, kind/feature

#385 docs: Update WeChatIMG
  docs/images/kosmos-WeChatIMG.png
Labels: kind/docs, size/XS, lgtm

#384 feat: supports the coexistence of multiple storage provisioning methods
  cmd/clustertree/cluster-manager/app/manager.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/leaf_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/oneway_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/root_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/leaf_pvc_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/oneway_pvc_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/root_pvc_controller.go
  pkg/utils/podutils/es.go
Labels: approved, lgtm, size/L, kind/feature

#386 cherry-pick: supports the coexistence of multiple storage provisioning methods
  cmd/clustertree/cluster-manager/app/manager.go
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/leaf_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/oneway_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/root_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/leaf_pvc_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/oneway_pvc_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/root_pvc_controller.go
  pkg/utils/podutils/es.go
Labels: approved, lgtm, size/L, kind/feature

#389 fix: delete Deprecated serviceAccount config
  deploy/clusterlink-elector.yml
  deploy/scheduler/deployment.yaml
  test/e2e/deploy/mysql-operator/mysqll-operator.yaml
Labels: approved, lgtm, kind/cleanup

#387 Optimize pvpvc code
  pkg/clustertree/cluster-manager/controllers/pod/leaf_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/leaf_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/root_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/leaf_pvc_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/root_pvc_controller.go
  pkg/utils/constants.go
Labels: approved, lgtm, size/L, kind/cleanup

#388 cherry-pick: optimize the pv and pvc codes
  pkg/clustertree/cluster-manager/controllers/pod/leaf_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/leaf_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pv/root_pv_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/leaf_pvc_controller.go
  pkg/clustertree/cluster-manager/controllers/pvc/root_pvc_controller.go
  pkg/utils/constants.go
Labels: approved, lgtm

#390 fix: macos make failed, add go clean cache(clean.sh)
  Makefile
  hack/build.sh
  hack/clean.sh
  hack/release.sh
  hack/util.sh
  hack/verify-all.sh
Labels: size/M, approved, lgtm

#392 feature: syncleaf CRD and informer init
  cmd/clustertree/cluster-manager/app/manager.go
  deploy/crds/kosmos.io_promotepolicies.yaml
  examples/promote_policy_demo.yaml
  pkg/apis/kosmos/v1alpha1/promotepolicy_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kosmos/v1alpha1/zz_generated.register.go
  pkg/clustertree/cluster-manager/controllers/promote_policy_controller.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/fake/fake_kosmos_client.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/fake/fake_promotepolicy.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/kosmos_client.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/promotepolicy.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/kosmos/v1alpha1/interface.go
  pkg/generated/informers/externalversions/kosmos/v1alpha1/promotepolicy.go
  pkg/generated/listers/kosmos/v1alpha1/expansion_generated.go
  pkg/generated/listers/kosmos/v1alpha1/promotepolicy.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/kosmosctl/manifest/manifest_crds.go
Labels: approved, size/XXL, kind/feature

#397 feature: implement controller for promotepolicy crd
  cmd/clustertree/cluster-manager/app/manager.go
  go.mod
  pkg/clustertree/cluster-manager/cluster_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/controllers/promote/backup/backup.go
  pkg/clustertree/cluster-manager/controllers/promote/backup/item_backupper.go
  pkg/clustertree/cluster-manager/controllers/promote/backup/item_collector.go
  pkg/clustertree/cluster-manager/controllers/promote/backup/pvc_backup_action.go
  pkg/clustertree/cluster-manager/controllers/promote/backup/rbac.go
  pkg/clustertree/cluster-manager/controllers/promote/backup/register_action.go
  pkg/clustertree/cluster-manager/controllers/promote/backup/service_account_backup_action.go
  pkg/clustertree/cluster-manager/controllers/promote/client/dynamic.go
  pkg/clustertree/cluster-manager/controllers/promote/constants/constants.go
  pkg/clustertree/cluster-manager/controllers/promote/detach/detach.go
  pkg/clustertree/cluster-manager/controllers/promote/detach/pod_detach_action.go
  pkg/clustertree/cluster-manager/controllers/promote/detach/pvc_detach_action.go
  pkg/clustertree/cluster-manager/controllers/promote/detach/register_action.go
  pkg/clustertree/cluster-manager/controllers/promote/discovery/helper.go
  pkg/clustertree/cluster-manager/controllers/promote/kuberesource/kuberesource.go
  pkg/clustertree/cluster-manager/controllers/promote/promote_policy_controller.go
  pkg/clustertree/cluster-manager/controllers/promote/requests/request.go
  pkg/clustertree/cluster-manager/controllers/promote/restore/pod_restore_action.go
  pkg/clustertree/cluster-manager/controllers/promote/restore/priority.go
  pkg/clustertree/cluster-manager/controllers/promote/restore/pv_restore_action.go
  pkg/clustertree/cluster-manager/controllers/promote/restore/register_action.go
  pkg/clustertree/cluster-manager/controllers/promote/restore/restore.go
  pkg/clustertree/cluster-manager/controllers/promote/utils/archive/extractor.go
  pkg/clustertree/cluster-manager/controllers/promote/utils/archive/filesystem.go
  pkg/clustertree/cluster-manager/controllers/promote/utils/archive/parser.go
  pkg/clustertree/cluster-manager/controllers/promote/utils/collections/includes_excludes.go
  pkg/clustertree/cluster-manager/controllers/promote/utils/filesystem/file_system.go
  pkg/clustertree/cluster-manager/controllers/promote/utils/kube/kube_utils.go
  pkg/clustertree/cluster-manager/controllers/promote/utils/shortcut_expander.go
  pkg/clustertree/cluster-manager/controllers/promote_policy_controller.go
  pkg/clustertree/cluster-manager/utils/leaf_resource_manager.go
  pkg/utils/podutils/pod.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, kind/feature
