Repository kosmos-io/kosmos, pull requests merged in 2024-04, with the labels that each got.

#436 Virtualcluster join controller
  cmd/clustertree-operator/app/options/options.go
  cmd/clustertree-operator/app/tree_operator.go
  pkg/kosmosctl/manifest/manifest_crds.go
  pkg/treeoperator/controller/virtualcluster_join_controller.go
Labels: approved, lgtm

#456 fix: LeafMode-Node supports taints migration(cherry-pick)
  pkg/clustertree/cluster-manager/utils/leaf_model_handler.go
Labels: approved, lgtm, kind/bug

#457 fix: fix 'automountServiceAccountToken' flag in the projected
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
Labels: approved, lgtm, kind/bug

#458 fix: fix 'automountServiceAccountToken' flag in the projected
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
Labels: approved, lgtm, kind/bug

#462 move some code to lifted
  cmd/clusterlink/controller-manager/app/controllerstarter.go
  cmd/clusterlink/controller-manager/app/options/options.go
  cmd/clustertree/cluster-manager/app/extersion_apps.go
  cmd/clustertree/cluster-manager/app/options/options.go
  pkg/clusterlink/controllers/calicoippool/calicoippool_controller.go
  pkg/clusterlink/controllers/cluster/cluster_controller.go
  pkg/clusterlink/controllers/context/context.go
  pkg/clusterlink/controllers/nodecidr/adapter.go
  pkg/clusterlink/controllers/nodecidr/nodecidr_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/serviceexport_controller.go
  pkg/clustertree/cluster-manager/controllers/mcs/serviceimport_controller.go
  pkg/clustertree/cluster-manager/controllers/pod/root_pod_controller.go
  pkg/clustertree/cluster-manager/extensions/daemonset/daemonset_controller.go
  pkg/clustertree/cluster-manager/extensions/daemonset/daemonset_mirror_controller.go
  pkg/clustertree/cluster-manager/extensions/daemonset/distribute_controller.go
  pkg/clustertree/cluster-manager/extensions/daemonset/pod_reflect_controller.go
  pkg/clustertree/cluster-manager/node-server/api/exec.go
  pkg/utils/lifted/env.go
  pkg/utils/lifted/expand.go
  pkg/utils/lifted/ratelimiterflag.go
  pkg/utils/lifted/worker.go
  pkg/utils/manager/resource.go
Labels: approved, lgtm, kind/cleanup

#461 add kosmos-scheduler release for Makefile of k8s 1.21.6
  .github/workflows/release_images.yml
  Makefile
Labels: lgtm

#467 modify codes for ci bug
  hack/util.sh
  pkg/kubenest/controlplane/component.go
  pkg/kubenest/controlplane/etcd.go
  pkg/kubenest/controlplane/rbac.go
  pkg/kubenest/util/helper.go
Labels: approved, lgtm

#469 modify virtualcluster's definition
  deploy/crds/kosmos.io_virtualclusters.yaml
  pkg/apis/kosmos/v1alpha1/virtualcluster_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/fake/fake_kosmos_client.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/fake/fake_virtualcluster.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/kosmos_client.go
  pkg/generated/clientset/versioned/typed/kosmos/v1alpha1/virtualcluster.go
  pkg/generated/informers/externalversions/kosmos/v1alpha1/interface.go
  pkg/generated/informers/externalversions/kosmos/v1alpha1/virtualcluster.go
  pkg/generated/listers/kosmos/v1alpha1/expansion_generated.go
  pkg/generated/listers/kosmos/v1alpha1/virtualcluster.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, lgtm, kind/cleanup

#470 modify virtualcluster's definition
  deploy/crds/kosmos.io_virtualclusters.yaml
  pkg/apis/kosmos/v1alpha1/podconvertpolicy_types.go
  pkg/apis/kosmos/v1alpha1/virtualcluster_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, kind/cleanup

#463 feat:add k8s in k8s websocket node agent for unjoin and join node
  cmd/kubenest/node-agent/Dockerfile
  cmd/kubenest/node-agent/OWNERS
  cmd/kubenest/node-agent/app.py
  cmd/kubenest/node-agent/build.sh
  cmd/kubenest/node-agent/clean.sh
  cmd/kubenest/node-agent/client.py
  cmd/kubenest/node-agent/count.py
  cmd/kubenest/node-agent/count.sh
  cmd/kubenest/node-agent/daemonset.yaml
  cmd/kubenest/node-agent/go/app.go
  cmd/kubenest/node-agent/go/app_test.go
  cmd/kubenest/node-agent/install.sh
  cmd/kubenest/node-agent/node-agent.service
  cmd/kubenest/node-agent/node-shell.yaml
  cmd/kubenest/node-agent/requirements.txt
  cmd/kubenest/node-agent/start.sh
Labels: approved, lgtm, kind/feature

#474 add hostport pool manager
  cmd/kubenest/operator/app/operator.go
  pkg/kubenest/controller/virtualcluster.node.controller/host_port_manager.go
  pkg/kubenest/controller/virtualcluster_execute_controller.go
  pkg/kubenest/controller/virtualcluster_init_controller.go
  pkg/kubenest/controlplane/apiserver.go
  pkg/kubenest/init.go
  pkg/kubenest/tasks/apiserver.go
  pkg/kubenest/tasks/data.go
Labels: approved, lgtm, kind/cleanup

#473 add component deployment functionality
  cmd/kubenest/operator/app/operator.go
  pkg/apis/kosmos/v1alpha1/virtualcluster_types.go
  pkg/kubenest/constants/constant.go
  pkg/kubenest/controller/kosmos/kosmos_join_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/node_controller.go
  pkg/kubenest/controller/virtualcluster_execute_controller.go
  pkg/kubenest/controller/virtualcluster_init_controller.go
  pkg/kubenest/init.go
  pkg/kubenest/tasks/data.go
  pkg/kubenest/tasks/manifests_components.go
Labels: approved, lgtm, kind/feature

#475 add externalIP for certificate-data
  pkg/kubenest/init.go
  pkg/kubenest/tasks/cert.go
  pkg/kubenest/tasks/data.go
  pkg/kubenest/util/cert/certs.go
Labels: approved, lgtm, kind/feature

#476 feat: add timestamp for virtualcluster
  deploy/crds/kosmos.io_virtualclusters.yaml
  pkg/apis/kosmos/v1alpha1/virtualcluster_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/kubenest/controller/virtualcluster.node.controller/join-worker.go
  pkg/kubenest/controller/virtualcluster.node.controller/node_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/share.go
  pkg/kubenest/controller/virtualcluster.nodepool.controller/nodepool.go
Labels: approved, lgtm, kind/feature

#477 delete control plane when deleting virtualcluster
  deploy/virtual-cluster-components-manifest-cm.yaml
  pkg/kubenest/constants/constant.go
  pkg/kubenest/controller/virtualcluster_execute_controller.go
  pkg/kubenest/controller/virtualcluster_init_controller.go
  pkg/kubenest/controlplane/apiserver.go
  pkg/kubenest/controlplane/component.go
  pkg/kubenest/controlplane/etcd.go
  pkg/kubenest/controlplane/service.go
  pkg/kubenest/init.go
  pkg/kubenest/tasks/apiserver.go
  pkg/kubenest/tasks/check.go
  pkg/kubenest/tasks/component.go
  pkg/kubenest/tasks/etcd.go
  pkg/kubenest/tasks/service.go
  pkg/kubenest/tasks/upload.go
  pkg/kubenest/util/helper.go
Labels: approved, lgtm, kind/feature

#483 add kosmos-scheduler release for Makefile
  Makefile
Labels: approved, lgtm, kind/feature

#481 add kosmos-scheduler release for Makefile
  Makefile
Labels: approved, lgtm, kind/feature

#482 add kosmos-scheduler release for Makefile
  Makefile
Labels: lgtm, kind/feature

#484 cherry-pick: add kosmos-scheduler release for Makefile
  Makefile
Labels: kind/feature

#478 feat: add core-dns
  .gitignore
  cmd/kubenest/operator/kubelet_node_helper.sh
  deploy/crds/kosmos.io_virtualclusters.yaml
  deploy/virtual-cluster-operator.yml
  pkg/apis/kosmos/v1alpha1/virtualcluster_types.go
  pkg/apis/kosmos/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/kubenest/constants/constant.go
  pkg/kubenest/controller/virtualcluster.node.controller/join-worker.go
  pkg/kubenest/controller/virtualcluster.node.controller/node_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/share.go
  pkg/kubenest/controller/virtualcluster.node.controller/unjoin-worker.go
  pkg/kubenest/init.go
  pkg/kubenest/tasks/coredns.go
  pkg/kubenest/tasks/data.go
Labels: approved, lgtm, kind/feature

#479 feat: add select host port for apiserver
  pkg/kubenest/constants/constant.go
  pkg/kubenest/controller/virtualcluster.node.controller/host_port_manager.go
  pkg/kubenest/controller/virtualcluster_init_controller.go
  pkg/kubenest/controlplane/apiserver.go
  pkg/kubenest/manifest/controlplane/apiserver/mainfests_deployment.go
  pkg/kubenest/util/address.go
Labels: approved, lgtm, kind/feature

#487 feat: add port selection for api server service
  pkg/kubenest/controller/virtualcluster.node.controller/hostport_manager.go
  pkg/kubenest/controlplane/service.go
  pkg/kubenest/manifest/controlplane/apiserver/mainfests_service.go
  pkg/kubenest/tasks/service.go
Labels: approved, lgtm, kind/feature

#486 deploy virtualcluster control plane on master nodes
  pkg/kubenest/manifest/controlplane/apiserver/mainfests_deployment.go
  pkg/kubenest/manifest/controlplane/etcd/mainfests_deployment.go
  pkg/kubenest/manifest/controlplane/kube-controller/manifests_deployment.go
  pkg/kubenest/manifest/controlplane/scheduler/manifest_deployment.go
  pkg/kubenest/tasks/manifests_components.go
Labels: approved, lgtm, kind/feature

#488 fix nodes assign func bug
  pkg/kubenest/controller/virtualcluster_init_controller.go
Labels: approved, lgtm, kind/bug

#489 feat: add ReleaseHostPort for api server and service
  pkg/kubenest/controller/virtualcluster_init_controller.go
  pkg/kubenest/controlplane/apiserver.go
  pkg/kubenest/controlplane/service.go
  pkg/kubenest/tasks/apiserver.go
  pkg/kubenest/tasks/service.go
Labels: approved, lgtm, kind/feature

#492 refactor: add workflow for node controller
  cmd/kubenest/operator/kubelet_node_helper.sh
  deploy/crds/kosmos.io_globalnodes.yaml
  deploy/virtual-cluster-operator.yml
  pkg/apis/kosmos/v1alpha1/global_node_types.go
  pkg/apis/kosmos/v1alpha1/virtualcluster_types.go
  pkg/kubenest/controller/virtualcluster.node.controller/constants.go
  pkg/kubenest/controller/virtualcluster.node.controller/env/env.go
  pkg/kubenest/controller/virtualcluster.node.controller/exector/exector.go
  pkg/kubenest/controller/virtualcluster.node.controller/join_worker.go
  pkg/kubenest/controller/virtualcluster.node.controller/node_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/unjoin_worker.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/join_tasks.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/unjoin_task.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/workflow.go
  pkg/kubenest/controller/virtualcluster_init_controller.go
  pkg/kubenest/manifest/controlplane/apiserver/mainfests_deployment.go
  pkg/kubenest/manifest/controlplane/etcd/mainfests_deployment.go
  pkg/kubenest/manifest/controlplane/kube-controller/manifests_deployment.go
  pkg/kubenest/manifest/controlplane/scheduler/manifest_deployment.go
  pkg/kubenest/tasks/coredns.go
  pkg/kubenest/util/node.go
Labels: approved, lgtm

#490 change node-agent to golang version to adapt for glibc 2.17
  cmd/kubenest/node-agent/Dockerfile
  cmd/kubenest/node-agent/agent.env
  cmd/kubenest/node-agent/daemonset.yaml
  cmd/kubenest/node-agent/go/app.go
  cmd/kubenest/node-agent/go/app_test.go
  cmd/kubenest/node-agent/go/go.mod
  cmd/kubenest/node-agent/go/go.sum
  cmd/kubenest/node-agent/node-agent.service
  deploy/virtual-cluster-operator.yml
Labels: approved, lgtm, kind/bug

#493 update globalnode status using `Patch`
  pkg/kubenest/controller/virtualcluster_init_controller.go
Labels: approved, lgtm, kind/bug

#494 feat: delete nodes that have already joined the virtual cluster from …
  pkg/kubenest/controller/virtualcluster.node.controller/env/env.go
  pkg/kubenest/controller/virtualcluster.node.controller/exector/exector.go
  pkg/kubenest/controller/virtualcluster.node.controller/exector/remote_scp.go
  pkg/kubenest/controller/virtualcluster.node.controller/node_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/join.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/task.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/unjoin.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/workflow.go
Labels: approved, lgtm, kind/feature

#495 add make node-agent target and improve the cmd return formate
  Makefile
  cluster/images/agent.Dockerfile
  cluster/images/buildx.agent.Dockerfile
  cmd/kubenest/node-agent/Dockerfile
  cmd/kubenest/node-agent/app.go
  cmd/kubenest/node-agent/app.py
  cmd/kubenest/node-agent/app_test.go
  cmd/kubenest/node-agent/client.py
  cmd/kubenest/node-agent/count.py
  cmd/kubenest/node-agent/daemonset.yaml
  cmd/kubenest/node-agent/go/go.mod
  cmd/kubenest/node-agent/go/go.sum
  cmd/kubenest/node-agent/node-shell.yaml
  cmd/kubenest/node-agent/requirements.txt
  go.mod
  hack/build.sh
  hack/docker.sh
  hack/node-agent/agent.env
  hack/node-agent/build.sh
  hack/node-agent/clean.sh
  hack/node-agent/count.sh
  hack/node-agent/install.sh
  hack/node-agent/node-agent.service
  hack/node-agent/start.sh
  hack/release.sh
  hack/util.sh
Labels: approved, lgtm, kind/bug

#497 fix virtualcluster apiserver deploy yaml bug
  pkg/kubenest/manifest/controlplane/apiserver/mainfests_deployment.go
Labels: approved, lgtm, kind/bug

#498 fix: add secret for node-agent websocket auth
  deploy/virtual-cluster-operator.yml
  pkg/kubenest/controller/virtualcluster.node.controller/env/env.go
Labels: approved, lgtm

#496 fix: change api server service ip to clusterip,port to clusterport
  pkg/kubenest/constants/constant.go
  pkg/kubenest/tasks/upload.go
Labels: approved, lgtm, kind/bug

#502 fix: add secret for node-agent websocket auth
  deploy/virtual-cluster-operator.yml
Labels: approved, lgtm

#501 feat: drain pod before delete node
  cmd/kubenest/operator/app/operator.go
  deploy/crds/kosmos.io_globalnodes.yaml
  pkg/apis/kosmos/v1alpha1/global_node_types.go
  pkg/kubenest/controller/virtualcluster.node.controller/env/env.go
  pkg/kubenest/controller/virtualcluster.node.controller/node_controller.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/join.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/task.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/task/unjoin.go
  pkg/kubenest/controller/virtualcluster.node.controller/workflow/workflow.go
  pkg/kubenest/util/node.go
  vendor/k8s.io/kubectl/pkg/drain/cordon.go
  vendor/k8s.io/kubectl/pkg/drain/default.go
  vendor/k8s.io/kubectl/pkg/drain/drain.go
  vendor/k8s.io/kubectl/pkg/drain/filters.go
  vendor/modules.txt
Labels: approved, lgtm

#500 add workflows ci for upload dev images
  .github/workflows/dev_images.yml
  .github/workflows/dev_images_personal.yml
  hack/cluster.sh
  hack/node-agent/node-agent.service
Labels: approved, kind/cleanup

#499 feat: add kosmos-hostports configmap template
  deploy/virtual-cluster-operator.yml
Labels: approved, lgtm, kind/feature
